// ─────────────────────────────────────────────────────────────────────────────
//  Base di conoscenza distillata dai paper scientifici forniti dall'utente.
//  GENERATO da tools/knowledge.mjs — non modificare a mano (verrà sovrascritto).
//  Vuoto = nessuna iniezione nei prompt (comportamento neutro, zero overhead).
// ─────────────────────────────────────────────────────────────────────────────

export const NUTRITION_PRINCIPLES = [
  `Esegui almeno 40 minuti di allenamento di forza a settimana per ridurre la mortalità per tutte le cause del 15%.`,
  `Punta a circa 60 minuti di forza a settimana per massimizzare la protezione contro le malattie cardiovascolari (-17%).`,
  `Dedica 30 minuti a settimana alla forza per ottenere la massima riduzione del rischio di cancro (-12%).`,
  `Raggiungi almeno 60 minuti di forza a settimana per ridurre l'incidenza del diabete di tipo 2 del 17%.`,
  `Limita l'allenamento di forza a 140 minuti a settimana, poiché i benefici sulla mortalità generale si saturano oltre questa soglia.`,
  `Combina l'allenamento di forza con l'attività aerobica per ridurre la mortalità per tutte le cause del 40%.`,
  `Utilizza la combinazione forza e cardio per abbassare il rischio di mortalità cardiovascolare del 46%.`,
  `Assumere creatina monoidrato con una dose di 0,1 g/kg di peso corporeo al giorno o circa 5 g fissi.`,
  `Omettere la fase di carico iniziale, preferendo una somministrazione costante nel tempo.`,
  `Combinare sistematicamente l'integrazione di creatina con un allenamento di resistenza per massimizzare la forza agli inferiori.`,
  `Utilizzare la creatina per aumentare significativamente la massa magra (lean tissue) nella popolazione anziana.`,
  `Prediligi interventi di durata inferiore a 32 settimane per massimizzare i guadagni di forza negli arti superiori.`,
  `Mantenere la coerenza dell'integrazione per evitare la riduzione di efficacia osservata oltre le 52 settimane.`,
  `Considerare la creatina monoidrato come protocollo sicuro e specifico per il contrasto della sarcopenia in età avanzata.`,
  `Adottare una finestra alimentare di 8 ore e un digiuno di 16 ore per massimizzare la perdita di grasso.`,
  `Eseguire il protocollo per almeno 8 settimane per ottenere una riduzione media del peso corporeo di 2.9 kg rispetto a una dieta standard.`,
  `Aspettarsi una riduzione specifica della massa grassa di 1.52 kg in più rispetto ai regimi alimentari tradizionali.`,
  `Preservare la massa magra e la forza muscolare combinando il digiuno intermittente con l'allenamento di resistenza.`,
  `Ridurre i livelli di insulina di 0.72 deviazioni standard attraverso la restrizione temporale dei pasti.`,
  `Abbattere il colesterolo totale in media di 9.44 mg/dL e il colesterolo LDL di 9.94 mg/dL.`,
  `Sfruttare il deficit calorico spontaneo di circa 174 kcal al giorno generato dalla restrizione temporale senza calcoli forzati.`,
  `Scegliere finestre temporali sostenibili come 12:00-20:00 o 13:00-21:00 per garantire l'aderenza a lungo termine.`,
  `Privilegia l'attività fisica regolare indipendentemente dalla tipologia specifica di esercizio scelto.`,
  `Inserire allenamenti di forza (RT) per contrastare la sarcopenia attivando la via mTOR e la sintesi proteica.`,
  `Praticare attività di endurance (ET) per ottimizzare il metabolismo ossidativo tramite la via PGC1-alfa.`,
  `Alternare sessioni di HIIT per massimizzare il VO2max, l'equilibrio e le funzioni esecutive.`,
  `Utilizzare l'esercizio aerobico moderato continuo (MICT) per migliorare l'umore e garantire l'aderenza a lungo termine.`,
  `Adottare rigorosamente la dieta mediterranea per ridurre l'infiammazione sistemica e il controllo metabolico.`,
  `Praticare yoga o tai chi per almeno 12 settimane per ridurre il dolore cronico (artrosi) del 66-75%.`,
  `Sfruttare l'HIIT per aumentare la popolazione di batteri intestinali produttori di acidi grassi a catena corta (SCFA).`,
  `Mantenere la diversità del microbiota intestinale attraverso il movimento fisico costante.`,
  `Combinare sinergicamente allenamento di forza, aerobica, dieta mediterranea e pratiche mente-corpo per massimizzare la longevità.`,
  `Privilegia il miglioramento della capacità cardiorespiratoria (VO2max) rispetto alla riduzione del peso corporeo per ridurre la mortalità.`,
  `Mantenere un elevato livello di fitness per annullare il rischio di aumento della mortalità anche in presenza di sovrappeso o obesità.`,
  `Evitare la condizione di non-fit poiché raddoppia il rischio di mortalità per qualsiasi causa, anche nei soggetti di normopeso.`,
  `Ridurre il rischio di mortalità cardiovascolare di 2-3 volte passando da uno stato di non-fit a uno di fit.`,
  `Considerare l'allenamento aerobico come l'intervento prioritario per mitigare i rischi metabolici legati all'eccesso corporeo.`,
  `Utilizzare la fitness cardiorespiratoria come principale predittore di longevità rispetto all'Indice di Massa Corporea (BMI).`,
  `Focalizzare sull'incremento della performance aerobica per prevenire il rischio di morte cardiovascolare, che raggiunge un HR di 3.35 negli obesi non-fit.`,
  `Mantenere la forza di presa sopra i 27 kg per gli uomini per ridurre il rischio di mortalità del 56%.`,
  `Mantenere la forza di presa sopra i 16 kg per le donne per ridurre il rischio di mortalità del 56%.`,
  `Incrementare la forza di presa di ogni 1 kg aggiuntivo riduce il rischio di mortalità per tutte le cause del 10%.`,
  `Utilizzare il dinamometro come strumento di screening periodico per valutare la resilienza fisiologica e la longevità.`,
  `Identificare e trattare la forza sotto le soglie europee per evitare un rischio di mortalità triplicato (37% vs 8%).`,
  `L'allenamento della forza per preservare lo stato nutrizionale e ridurre la prevalenza di malattie croniche.`,
  `Monitorare la forza di presa nel tempo come predittore robusto dell'invecchiamento biologico.`,
  `Consumare fibre fermentabili per aumentare gli acidi grassi a catena corta (SCFA), specifici per migliorare il sonno non-REM.`,
  `Assumere polifenoli da frutta, verdura, tè e noci per stimolare la produzione di SCFA e aminoacidi ramificati.`,
  `Privilegiare grassi insaturi (omega-3, olio d'oliva, pesce) per aumentare la diversità microbica ed evitare i grassi saturi.`,
  `Integrare 300 mg di GABA al giorno per migliorare significativamente l'efficienza del sonno.`,
  `Consumare i pasti principali nella prima parte della giornata per non interferire con i ritmi circadiani.`,
  `Mantenere orari dei pasti regolari per stabilizzare il metabolismo e il microbiota intestinale.`,
  `Includere una varietà elevata di vegetali, cereali integrali, legumi, noci e semi per favorire la produzione di serotonina e melatonina.`,
  `Eliminare diete ad alto contenuto di zuccheri e carni processate per prevenire peggioramenti del microbiota.`,
  `Assumere tra 70 mL e 250 mL di succo di barbabietola a dose per ridurre la pressione sistolica.`,
  `Somministrare un dosaggio di nitrati compreso tra 6,2 e 12,8 mmol per ogni assunzione.`,
  `Mantenere l'assunzione per un periodo variabile da 3 a 60 giorni per ottenere benefici sulla pressione arteriosa sistolica.`,
  `Aspettarsi una riduzione media della pressione sistolica di circa 5 mmHg dopo l'integrazione.`,
  `Sfruttare i nitrati come precursori dell'ossido nitrico per migliorare la funzione endoteliale e la vasodilatazione vascolare.`,
  `Utilizzare succo di barbabietola specificamente per la gestione dell'ipertensione arteriosa sistolica lieve.`,
  `Privilegia il controllo della pressione sistolica poiché la pressione diastolica non mostra variazioni statisticamente significative.`,
  `Effettuare almeno 2-3 sessioni di sauna a settimana per ridurre il rischio di mortalità cardiovascolare del 25%.`,
  `Puntare a una frequenza di 4-7 sessioni a settimana per ottenere una riduzione del rischio cardiovascolare fino al 77%.`,
  `Raggiungere una durata totale settimanale superiore ai 45 minuti di sauna per una protezione significativa del cuore.`,
  `Mantenere la durata della singola sessione di circa 19 minuti o più per massimizzare i benefici emetici.`,
  `Operare a una temperatura media della sauna efficace compresa tra i 75°C e gli 80°C.`,
  `Sfruttare la relazione lineare tra frequenza e protezione: il rischio cala proporzionalmente al numero di sessioni accumulate.`,
  `Trattare l'esposizione al calore come uno stimolo ormetico regolare per il miglioramento della salute cardiovascolare a lungo termine.`,
  `Priorilegiare il sonno profondo a onde lente (N3) nella prima metà della notte per favorire la clearance dell'80-90% delle scorie metaboliche.`,
  `Adottare la posizione laterale sul fianco destro per massimizzare l'efficienza del drenaggio glinfatico rispetto alla posizione supina o pronaa.`,
  `Eseguire almeno 150 minuti di attività fisica moderata o 75 minuti di attività vigorosa a settimana per migliorare la frequenza cardiaca a riposo e la polarizzazione dell'acquaporina AQP4.`,
  `Assumere regolarmente Omega-3 (n-3 PUFA di origine marina) per mantenere la polarizzazione di AQP4 e aumentare l'afflusso di liquido cerebrospinale.`,
  `Applicare protocolli di digiuno intermittente o alternato per ridurre i depositi di amiloide-beta tramite l'attivazione di AQP4 via beta-idrossibutirrato.`,
  `Evitare il consumo di alcol in dosi superiori a 0.5 g/kg di peso corporeo per non ridurre drasticamente il trasporto glinfatico.`,
  `Limitare l'uso di sonniferi come lo Zolpidem, poiché sopprime le oscillazioni di noradrenalina necessarie alla vasomozione che lava il cervello.`,
  `Ridurre lo stress cronico e la privazione del sonno per prevenire la degradazione di AQP4 e il conseguente accumulo di proteine tossiche.`,
  `Assumere 15 grammi di gelatina o collagene idrolizzato circa 30-60 minuti prima di iniziare l'attività fisica.`,
  `Integrare almeno 50 milligrammi di vitamina C insieme alla dose di collagene per agire come cofattore essenziale nella sintesi proteica.`,
  `Eseguire un carico meccanico specifico per i tendini per una durata compresa tra i 6 e i 10 minuti dopo l'integrazione.`,
  `Ripetere il protocollo di integrazione e carico fino a 3 volte al giorno per massimizzare la risposta dei tessuti connettivi.`,
  `Utilizzare esercizi brevi e ad alta intensità, come il salto della corda, per stimolare il flusso sanguigno verso i tessuti articolari scarsamente vascolarizzati.`,
  `Garantire una dose minima di 15 grammi di gelatina, poiché dosi inferiori ai 5 grammi non risultano efficaci nel raddoppiare la sintesi di collagene.`,
  `Sincronizzare il timing dell'assunzione con l'esercizio per sfruttare la massima disponibilità di amminoacidi nel sito del tendine durante lo stress meccanico.`,
  `Assumere una dose giornaliera di almeno 2-3 grammi di EPA e DHA combinati per supportare la salute cardiovascolare e cerebrale.`,
  `Utilizzare 4 grammi di olio di pesce al giorno (equivalenti a 1,86 g di EPA e 1,50 g di DHA) per massimizzare la risposta anabolica muscolare negli adulti sopra i sessanta anni.`,
  `Evitare di fareamento all'integrazione di omega-3 per un aumento diretto della sintesi proteica miofibrillare nei giovani già sottoposti a un allenamento di forza.`,
  `Non prioritizzare l'assunzione di olio di pesce immediatamente dopo la sessione di allenamento, in quanto potrebbe attenuare i segnali anabolici post-esercizio.`,
  `Sfruttare l'integrazione di omega-3 esclusivamente per la gestione della risposta infiammatoria e il miglioramento del recupero e del sistema glinfatico.`,
  `Privilegiare integratori di alta qualità caratterizzati da un elevato indice omega-3 per garantire la concentrazione di acidi grassi attivi.`,
  `Considerare gli omega-3 come uno strumento di protezione sistemica a lungo termine piuttosto che come un acceleratore immediato dell'ipertrofia muscolare negli atleti.`,
  `Assumere un totale giornaliero di proteine compreso tra 1,6 e 2,2 grammi per chilogramo di peso corporeo, ovvero tra 140 e 190 grammi per un individuo di 86 kg.`,
  `Dosare circa 34 grammi di proteine di alta qualità a ogni pasto per massimizzare la sintesi proteica muscolare individuale.`,
  `Garantire la presenza di almeno 2,5-3 grammi di leucina in ogni pasto proteico per attivare pienamente la risposta anabolica muscolare.`,
  `Distribuire l'apporto proteico in 3 o 4 pasti bilanciati durante la giornata invece di concentrarlo in una o due occasioni.`,
  `Consumare tra i 30 e i 40 grammi di proteine lento rilascio come caseina prima del sonno per stimolare la sintesi notturna e il recupero.`,
  `Evitare di superare la soglia di 0,4 grammi di proteine per chilogramo a pasto, poiché l'eccesso viene ossidato anziché utilizzato per la crescita muscolare.`,
  `Privilegiare fonti proteiche ad alto valore biologico come siero del latte, carne, uova o pesce per assicurare il corretto profilo amminoacidico necessario.`,
  `Consumare germogli di broccoli di 3 giorni per ottenere una concentrazione di glucorafanina fino 100 volte superiore rispetto al broccolo maturo.`,
  `Assumere una dose giornaliera compresa tra 100 e i 200 micromol di glucorafanina per attivare efficacement i meccanismi di detossificazione cellulare.`,
  `Masticare accuratamente i germogli di broccoli crudi per consentire all'enzima mirosinasi di convertire la glucorafanina in sulforafano attivo.`,
  `Aggiungere polvere di senape ai broccoli cotti per ripristinare l'attività della mirosinasi, necessaria alla produzione di sulforafano.`,
  `Seguire un protocollo di 12 settimane con 40 micromol di sulforafano al giorno per aumentare l'escrezione di tossine ambientali come il benzene del 61%.`,
  `Utilizzare il sulforafano per stimolare la produzione endogena di oltre 600 geni protettivi, tra cui gli enzimi NQO1 e le GST.`,
  `Sfruttare l'integrazione di sulforafano per estendere il tempo di raddoppio del PSA nel tumore alla prostata, quasi raddoppiandolo rispetto al placebo.`,
  `Prediligere l'assunzione di sulforafano rispetto agli antiossidanti isolati per attivare una risposta antiossidante endogena più potente e duratura.`,
  `Eseguire l'allenamento in Zona 2 mantenendo la concentrazione di lattato ematico stabile al di sotto della soglia di 2 mmol/L.`,
  `Mantenere un ritmo conversazionale che permetta di parlare in frasi intere e di respirare esclusivamente con il naso senza difficoltà.`,
  `Programmare da 3 a 4 sessioni di allenamento a settimana con una durata compresa tra i 45 e i 90 minuti ciascuna.`,
  `Stimolare la biogenesi mitocondriale per massimizzare l'ossidazione dei grassi attraverso le fibre muscolari di tipo I.`,
  `Sviluppare la capacità di clearance del lattato sfruttando il meccanismo del 'lactate-shuttle' per migliorare la flessibilità metabolica.`,
  `Utilizzare l'intensità di Zona 2 per ottimizzare il bilancio redox e il controllo glicemico a lungo termine.`,
  `Costruire una base aerobica solida in Zona 2 per aumentare le prestazioni nelle sessioni ad alta intensità e ridurre i tempi di recupero.`,
  `Mantenere una durata del sonno compresa tra 7 e 9 ore per notte per preservare i livelli fisiologici di testosterone.`,
  `Limitare il sonno a meno di 5 ore e 48 minuti a notte per evitare una riduzione del testosterone diurno tra il 10% e il 15%.`,
  `Evitare la restrizione del sonno poiché una sola settimana equivale ormonmente a un invecchiamento di 10-15 anni.`,
  `Priorità assoluta al sonno considerato come variabile non negoziabile per massimizzare l'effetto dell'allenamento e della dieta ipertrofica.`,
  `Monitorare la qualità del riposo per prevenire il crollo del vigore fisico e dell'energia, che possono ridursi drasticamente dopo una settimana di deprivazione.`,
  `Considerare il riposo notturno come il principale strumento anabolico per il mantenimento della massa muscolare e della forza.`,
];

export const KNOWLEDGE_SOURCES = [
  { title: `allenamento forza dose mortalita`, topic: `Dose ottimale di allenamento di forza e `, principles: 7 },
  { title: `creatina anziani forza massa`, topic: `Creatina e allenamento di forza nei sogg`, principles: 7 },
  { title: `digiuno 16 8 allenamento forza`, topic: `Digiuno 16:8 e allenamento di forza`, principles: 8 },
  { title: `esercizio nutrizione longevita`, topic: `Esercizio e nutrizione per la longevità `, principles: 10 },
  { title: `fitness cardiorespiratoria vs peso mortalita`, topic: `fitness cardiorespiratoria e mortalità`, principles: 7 },
  { title: `forza presa mano biomarcatore mortalita`, topic: `Forza di presa mano come biomarcatore di`, principles: 7 },
  { title: `microbioma intestinale sonno`, topic: `Asse intestino-cervello e qualità del so`, principles: 8 },
  { title: `nitrati barbabietola pressione`, topic: `Nitrati della barbabietola e pressione a`, principles: 7 },
  { title: `sauna mortalita cardiovascolare`, topic: `Sauna e mortalità cardiovascolare`, principles: 7 },
  { title: `sistema glinfatico sonno pulizia cervello`, topic: `Ottimizzazione del sistema glinfatico e `, principles: 8 },
  { title: `gelatina vitamina c tendini collagene`, topic: `Ottimizzazione della sintesi di collagen`, principles: 7 },
  { title: `omega3 sintesi proteica recupero`, topic: `Omega-3, sintesi proteica e recupero`, principles: 7 },
  { title: `proteine per pasto leucina sintesi muscolare`, topic: `Ottimizzazione' apporto proteico per l'i`, principles: 7 },
  { title: `sulforafano germogli broccoli nrf2`, topic: `Attivazione della via NRF2 tramite sulfo`, principles: 8 },
  { title: `zone2 lattato mitocondri san millan`, topic: `Allenamento in Zona 2 e funzione mitocon`, principles: 7 },
  { title: `sonno testosterone uomini giovani`, topic: `impatto del sonno sul testosterone nei g`, principles: 6 },
];

export function knowledgePrompt(max = 3500) {
  if (!Array.isArray(NUTRITION_PRINCIPLES) || !NUTRITION_PRINCIPLES.length) return '';
  let body = NUTRITION_PRINCIPLES.map((p, i) => `${i + 1}. ${p}`).join('\n');
  if (body.length > max) body = body.slice(0, max).replace(/\n[^\n]*$/, '') + '\n…';
  return `\n\nPRINCIPI SCIENTIFICI (distillati da paper forniti dall'utente — fonda i consigli su questi e citali quando pertinenti):\n${body}`;
}
