// ─────────────────────────────────────────────────────────────────────────────
//  Base di conoscenza distillata dai paper scientifici forniti dall'utente.
//  GENERATO da tools/knowledge.mjs — non modificare a mano (verrà sovrascritto).
//  Vuoto = nessuna iniezione nei prompt (comportamento neutro, zero overhead).
// ─────────────────────────────────────────────────────────────────────────────

export const NUTRITION_PRINCIPLES = [
  `Privilegia l'attività fisica regolare indipendentemente dalla tipologia specifica di esercizio scelto.`,
  `Inserire allenamenti di forza (RT) per contrastare la sarcopenia attivando la via mTOR e la sintesi proteica.`,
  `Praticare attività di endurance (ET) per ottimizzare il metabolismo ossidativo tramite la via PGC1-alfa.`,
  `Alternare sessioni di HIIT per massimizzare il VO2max, l'equilibrio e le funzioni esecutive.`,
  `Utilizzare l'esercizio aerobico moderato continuo (MICT) per migliorare l'umore e garantire l'aderenza a lungo termine.`,
  `Adottare rigorosamente la dieta mediterranea per ridurre l'infiammazione sistemica e il controllo metabolico.`,
  `Praticare yoga o tai chi per almeno 12 settimane per ridurre il dolore cronico (artrosi) del 66-75%.`,
  `Sfruttare l'HIIT per aumentare la popolazione di batteri intestinali produttori di acidi grassi a catena corta (SCFA).`,
  `Mantenere la diversità del microbiota intestinale attraverso il movimento fisico costante.`,
  `Combinare sinergicamente allenamento di forza, aerobica, dieta mediterranea e pratiche mente-corpo per massimizzare la longevità.`,
  `Privilegia il miglioramento della capacità cardiorespiratoria (VO2max) rispetto alla riduzione del peso corporeo per ridurre la mortalità.`,
  `Mantenere un elevato livello di fitness per annullare il rischio di aumento della mortalità anche in presenza di sovrappeso o obesità.`,
  `Evitare la condizione di non-fit poiché raddoppia il rischio di mortalità per qualsiasi causa, anche nei soggetti di normopeso.`,
  `Ridurre il rischio di mortalità cardiovascolare di 2-3 volte passando da uno stato di non-fit a uno di fit.`,
  `Considerare l'allenamento aerobico come l'intervento prioritario per mitigare i rischi metabolici legati all'eccesso corporeo.`,
  `Utilizzare la fitness cardiorespiratoria come principale predittore di longevità rispetto all'Indice di Massa Corporea (BMI).`,
  `Focalizzare sull'incremento della performance aerobica per prevenire il rischio di morte cardiovascolare, che raggiunge un HR di 3.35 negli obesi non-fit.`,
  `Mantenere la forza di presa sopra i 27 kg per gli uomini per ridurre il rischio di mortalità del 56%.`,
  `Mantenere la forza di presa sopra i 16 kg per le donne per ridurre il rischio di mortalità del 56%.`,
  `Incrementare la forza di presa di ogni 1 kg aggiuntivo riduce il rischio di mortalità per tutte le cause del 10%.`,
  `Utilizzare il dinamometro come strumento di screening periodico per valutare la resilienza fisiologica e la longevità.`,
  `Identificare e trattare la forza sotto le soglie europee per evitare un rischio di mortalità triplicato (37% vs 8%).`,
  `L'allenamento della forza per preservare lo stato nutrizionale e ridurre la prevalenza di malattie croniche.`,
  `Monitorare la forza di presa nel tempo come predittore robusto dell'invecchiamento biologico.`,
  `Consumare fibre fermentabili per aumentare gli acidi grassi a catena corta (SCFA), specifici per migliorare il sonno non-REM.`,
  `Assumere polifenoli da frutta, verdura, tè e noci per stimolare la produzione di SCFA e aminoacidi ramificati.`,
  `Privilegiare grassi insaturi (omega-3, olio d'oliva, pesce) per aumentare la diversità microbica ed evitare i grassi saturi.`,
  `Integrare 300 mg di GABA al giorno per migliorare significativamente l'efficienza del sonno.`,
  `Consumare i pasti principali nella prima parte della giornata per non interferire con i ritmi circadiani.`,
  `Mantenere orari dei pasti regolari per stabilizzare il metabolismo e il microbiota intestinale.`,
  `Includere una varietà elevata di vegetali, cereali integrali, legumi, noci e semi per favorire la produzione di serotonina e melatonina.`,
  `Eliminare diete ad alto contenuto di zuccheri e carni processate per prevenire peggioramenti del microbiota.`,
  `Assumere tra 70 mL e 250 mL di succo di barbabietola a dose per ridurre la pressione sistolica.`,
  `Somministrare un dosaggio di nitrati compreso tra 6,2 e 12,8 mmol per ogni assunzione.`,
  `Mantenere l'assunzione per un periodo variabile da 3 a 60 giorni per ottenere benefici sulla pressione arteriosa sistolica.`,
  `Aspettarsi una riduzione media della pressione sistolica di circa 5 mmHg dopo l'integrazione.`,
  `Sfruttare i nitrati come precursori dell'ossido nitrico per migliorare la funzione endoteliale e la vasodilatazione vascolare.`,
  `Utilizzare succo di barbabietola specificamente per la gestione dell'ipertensione arteriosa sistolica lieve.`,
  `Privilegia il controllo della pressione sistolica poiché la pressione diastolica non mostra variazioni statisticamente significative.`,
  `Effettuare almeno 2-3 sessioni di sauna a settimana per ridurre il rischio di mortalità cardiovascolare del 25%.`,
  `Puntare a una frequenza di 4-7 sessioni a settimana per ottenere una riduzione del rischio cardiovascolare fino al 77%.`,
  `Raggiungere una durata totale settimanale superiore ai 45 minuti di sauna per una protezione significativa del cuore.`,
  `Mantenere la durata della singola sessione di circa 19 minuti o più per massimizzare i benefici emetici.`,
  `Operare a una temperatura media della sauna efficace compresa tra i 75°C e gli 80°C.`,
  `Sfruttare la relazione lineare tra frequenza e protezione: il rischio cala proporzionalmente al numero di sessioni accumulate.`,
  `Trattare l'esposizione al calore come uno stimolo ormetico regolare per il miglioramento della salute cardiovascolare a lungo termine.`,
  `Priorilegiare il sonno profondo a onde lente (N3) nella prima metà della notte per favorire la clearance dell'80-90% delle scorie metaboliche.`,
  `Adottare la posizione laterale sul fianco destro per massimizzare l'efficienza del drenaggio glinfatico rispetto alla posizione supina o pronaa.`,
  `Eseguire almeno 150 minuti di attività fisica moderata o 75 minuti di attività vigorosa a settimana per migliorare la frequenza cardiaca a riposo e la polarizzazione dell'acquaporina AQP4.`,
  `Assumere regolarmente Omega-3 (n-3 PUFA di origine marina) per mantenere la polarizzazione di AQP4 e aumentare l'afflusso di liquido cerebrospinale.`,
  `Applicare protocolli di digiuno intermittente o alternato per ridurre i depositi di amiloide-beta tramite l'attivazione di AQP4 via beta-idrossibutirrato.`,
  `Evitare il consumo di alcol in dosi superiori a 0.5 g/kg di peso corporeo per non ridurre drasticamente il trasporto glinfatico.`,
  `Limitare l'uso di sonniferi come lo Zolpidem, poiché sopprime le oscillazioni di noradrenalina necessarie alla vasomozione che lava il cervello.`,
  `Ridurre lo stress cronico e la privazione del sonno per prevenire la degradazione di AQP4 e il conseguente accumulo di proteine tossiche.`,
  `Assumere 15 grammi di gelatina o collagene idrolizzato circa 30-60 minuti prima di iniziare l'attività fisica.`,
  `Integrare almeno 50 milligrammi di vitamina C insieme alla dose di collagene per agire come cofattore essenziale nella sintesi proteica.`,
  `Eseguire un carico meccanico specifico per i tendini per una durata compresa tra i 6 e i 10 minuti dopo l'integrazione.`,
  `Ripetere il protocollo di integrazione e carico fino a 3 volte al giorno per massimizzare la risposta dei tessuti connettivi.`,
  `Utilizzare esercizi brevi e ad alta intensità, come il salto della corda, per stimolare il flusso sanguigno verso i tessuti articolari scarsamente vascolarizzati.`,
  `Garantire una dose minima di 15 grammi di gelatina, poiché dosi inferiori ai 5 grammi non risultano efficaci nel raddoppiare la sintesi di collagene.`,
  `Sincronizzare il timing dell'assunzione con l'esercizio per sfruttare la massima disponibilità di amminoacidi nel sito del tendine durante lo stress meccanico.`,
  `Assumere una dose giornaliera di almeno 2-3 grammi di EPA e DHA combinati per supportare la salute cardiovascolare e cerebrale.`,
  `Utilizzare 4 grammi di olio di pesce al giorno (equivalenti a 1,86 g di EPA e 1,50 g di DHA) per massimizzare la risposta anabolica muscolare negli adulti sopra i sessanta anni.`,
  `Non fare affidamento sull’integrazione di omega-3 per un aumento diretto della sintesi proteica miofibrillare nei giovani già sottoposti a un allenamento di forza.`,
  `Non prioritizzare l'assunzione di olio di pesce immediatamente dopo la sessione di allenamento, in quanto potrebbe attenuare i segnali anabolici post-esercizio.`,
  `Sfruttare l'integrazione di omega-3 esclusivamente per la gestione della risposta infiammatoria e il miglioramento del recupero e del sistema glinfatico.`,
  `Privilegiare integratori di alta qualità caratterizzati da un elevato indice omega-3 per garantire la concentrazione di acidi grassi attivi.`,
  `Considerare gli omega-3 come uno strumento di protezione sistemica a lungo termine piuttosto che come un acceleratore immediato dell'ipertrofia muscolare negli atleti.`,
  `Assumere un totale giornaliero di proteine compreso tra 1,6 e 2,2 grammi per chilogrammo di peso corporeo, ovvero tra 140 e 190 grammi per un individuo di 86 kg.`,
  `Dosare circa 34 grammi di proteine di alta qualità a ogni pasto per massimizzare la sintesi proteica muscolare individuale.`,
  `Garantire la presenza di almeno 2,5-3 grammi di leucina in ogni pasto proteico per attivare pienamente la risposta anabolica muscolare.`,
  `Distribuire l'apporto proteico in 3 o 4 pasti bilanciati durante la giornata invece di concentrarlo in una o due occasioni.`,
  `Consumare tra i 30 e i 40 grammi di proteine a lento rilascio come caseina prima del sonno per stimolare la sintesi notturna e il recupero.`,
  `Evitare di superare la soglia di 0,4 grammi di proteine per chilogrammo a pasto, poiché l'eccesso viene ossidato anziché utilizzato per la crescita muscolare.`,
  `Privilegiare fonti proteiche ad alto valore biologico come siero del latte, carne, uova o pesce per assicurare il corretto profilo amminoacidico necessario.`,
  `Consumare germogli di broccoli di 3 giorni per ottenere una concentrazione di glucorafanina fino 100 volte superiore rispetto al broccolo maturo.`,
  `Assumere una dose giornaliera compresa tra 100 e i 200 micromol di glucorafanina per attivare efficacement i meccanismi di detossificazione cellulare.`,
  `Masticare accuratamente i germogli di broccoli crudi per consentire all'enzima mirosinasi di convertire la glucorafanina in sulforafano attivo.`,
  `Aggiungere polvere di senape ai broccoli cotti per ripristinare l'attività della mirosinasi, necessaria alla produzione di sulforafano.`,
  `Seguire un protocollo di 12 settimane con 40 micromol di sulforafano al giorno per aumentare l'escrezione di tossine ambientali come il benzene del 61%.`,
  `Utilizzare il sulforafano per stimolare la produzione endogena di oltre 600 geni protettivi, tra cui gli enzimi NQO1 e le GST.`,
  `Sfruttare l'integrazione di sulforafano per estendere il tempo di raddoppio del PSA nel tumore alla prostata, quasi raddoppiandolo rispetto al placebo.`,
  `Prediligere l'assunzione di sulforafano rispetto agli antiossidanti isolati per attivare una risposta antiossidante endogena più potente e duratura.`,
  `Eseguire l'allenamento in Zona 2 mantenendo la concentrazione di lattato ematico stabile al di sotto della soglia di 2 mmol/L.`,
  `Mantenere un ritmo conversazionale che permetta di parlare in frasi intere e di respirare esclusivamente con il naso senza difficoltà.`,
  `Programmare da 3 a 4 sessioni di allenamento a settimana con una durata compresa tra i 45 e i 90 minuti ciascuna.`,
  `Stimolare la biogenesi mitocondriale per massimizzare l'ossidazione dei grassi attraverso le fibre muscolari di tipo I.`,
  `Sviluppare la capacità di clearance del lattato sfruttando il meccanismo del 'lactate-shuttle' per migliorare la flessibilità metabolica.`,
  `Utilizzare l'intensità di Zona 2 per ottimizzare il bilancio redox e il controllo glicemico a lungo termine.`,
  `Costruire una base aerobica solida in Zona 2 per aumentare le prestazioni nelle sessioni ad alta intensità e ridurre i tempi di recupero.`,
  `Mantenere una durata del sonno compresa tra 7 e 9 ore per notte per preservare i livelli fisiologici di testosterone.`,
  `Limitare il sonno a meno di 5 ore e 48 minuti a notte per evitare una riduzione del testosterone diurno tra il 10% e il 15%.`,
  `Evitare la restrizione del sonno poiché una sola settimana equivale ormonmente a un invecchiamento di 10-15 anni.`,
  `Priorità assoluta al sonno considerato come variabile non negoziabile per massimizzare l'effetto dell'allenamento e della dieta ipertrofica.`,
  `Monitorare la qualità del riposo per prevenire il crollo del vigore fisico e dell'energia, che possono ridursi drasticamente dopo una settimana di deprivazione.`,
  `Considerare il riposo notturno come il principale strumento anabolico per il mantenimento della massa muscolare e della forza.`,
  `Evitare l'assunzione di caffeina per almeno 6 ore prima di coricarsi per prevenire una riduzione del sonno totale superiore a un'ora.`,
  `Limitare l'ultima assunzione di caffeina entro le ore 14:00 o 15:00 se si prevede di andare a letto tra le 22:00 e le 23:00.`,
  `Sii consapevole che 400 mg di caffeina assunti 6 ore prima del sonno compromettono significativamente il sonno profondo a onde lente.`,
  `Non assumere caffeina nelle 3 ore precedenti il sonno, poiché aumenta il tempo necessario all'addormentarsi di circa 17 minuti.`,
  `Non affidarsi alla percezione soggettiva della qualità del sonno, poiché la caffeina può danneggiare il riposo senza essere percepita.`,
  `Considerare che l'emivita della caffeina varia tra 4 e 11 ore, indicando che metà della sostanza rimane attiva nel corpo dopo 6 ore.`,
  `Anticipare ulteriormente l'assunzione di caffè se si è classificati come metabolizzatori lenti della sostina.`,
  `Limitare la caffeina per impedire il blocco dei recettori dell'adenosina, responsabili della naturale pressione del sonnolenza.`,
  `Consumare ogni giorno alimenti fermentati come yogurt, kefir, kimchi e verdure in salamoia per aumentare la diversità del microbioma.`,
  `Aumentare le porzioni giornaliere di cibi fermentati per ottenere un incremento più significativo della diversità microbica intestinale.`,
  `Adottare una dieta ricca di fermentati per ridurre specificamente 19 marcatori proteici di infiammzione in un arco di 10 settimane.`,
  `Utilizzare i cibi fermentati per diminuire l'attivazione di quattro tipologie di cellule immunitarie.`,
  `Privilegiare l'incremento dei fermentati rispetto alla sola fibra se l'obiettivo è un effetto antinfiammatorio rapido nel breve termine.`,
  `Integrare crauti non pastorizzati e yogurt con fermenti vivi nel regime alimentare per modulare lo stato immunitario in modo efficace della fibra.`,
  `Combinare l'assunzione di cibi fermentati con un adeguato apporto di fibre per massimizzare la salute del microbiota nel lungo periodo.`,
  `Somministrare una dose singola di creatina di 0,35 g al kg di peso corporeo per contrastare il deficit cognitivo dovuto alla privazione di sonno.`,
  `Utilizzare la creatina per migliorare la memoria di lavoro di circa il 10% in contesti di stress da sonno prolungato.`,
  `Aumentare la velocità di elaborazione di compiti logici, linguistici e matematici tra il 16% e il 29% tramite l'assunzione della dose indicata.`,
  `Ridurre la fatica soggettiva dell'8% e migliorare la vigilanza psicomotoria dopo 21 ore di veglia consecutiva.`,
  `Programmare l'assunzione della dose acuta prevedendo il picco di efficacia cognitiva tra le 3,5 e le 9 ore successive al consumo.`,
  `Supportare la funzione cerebrale stabilizzando i livelli di fosfocreatina e ATP nel neuroni, prevenendo l'acidificazione del tessuto causata dalla mancanza di riposo.`,
  `Mantenere un'integrazione quotidiana standard di circa 5 grammi per garantire la saturazione delle riserve cerebrali e ridurre la necessità di dosi di emergenza.`,
  `Incrementare il VO2max è il predittore più critico per la riduzione del rischio di mortalità a lungo termine.`,
  `Raggiungere un livello di fitness elite, definito come almeno 2 deviazioni standard sopra la media per età e sesso, riduce il rischio di morte dell'80% rispetto a chi ha una bassa fitness.`,
  `Non esiste un limite superiore ai benefici della fitness cardiorespiratoria: ogni ulteriore miglioramento del VO2max continua a ridurre il rischio di decesso.`,
  `Mantenere una bassa fitness cardiorespiratoria rappresenta un rischio di morte superiore o uguale a quello del fumo o del diabete di tipo 2.`,
  `La condizione di 'non-fit' ha un impatto negativo sulla mortalità più significativo rispetto alla sola presenza di malattia coronarica o insufficienza renale.`,
  `È prioritenziale prioritiare la costruzione di un VO2max elevato fin dalla giovane età come strategia principale per l'aumento dell'aspgevità.`,
  `Implementare un regime di allenamento che combini attività di base in Zona 2 con sessioni ad alta intensità (HIIT) per massimizzare la capacità cardiorespiratoria.`,
  `L'immersione in acqua a temperatura compresa tra 10°C e 15°C provoca un aumento della noradrenalina plasmatica del 530%.`,
  `L'esposizione al freddo determina un incremento della dopamina nel plasma pari al 250%.`,
  `L'elevata concentrazione di dopamina indotta dal freddo rimane sostenuto per oltre 2 ore senza causare il crollo tipico degli stimolanti o zuccheri.`,
  `Eseguire l'immersione fredda per 1 ai 3 minuti per aumentare la vigilanza, il tono dell'umore e la concentrazione.`,
  `Evitare l'esposizione al freddo immediatamente dopo una sessione di allenamento di ipertrofia per non inibire l'adattamento muscolare.`,
  `Programmare le sessioni di freddo nei giorni di riposo o in precedenza all'allenamento di forza per massimizzare la crescita muscolare.`,
  `Utilizzare l'immersione fredda come strategia mattutina o per contrastare i cali di energia nel periodoidiano.`,
  `Introdurre gradualmente l'esposizione al freddo e prestare estrema cautela in presenza di patologie cardiache.`,
  `Esponiti alla luce naturale entro i primi 30-60 minuti dal risveglio per attivare la risposta del cortisolo al mattino.`,
  `Mantieni l'esposizione alla luce mattutina per una durata compresa tra 5 e 15 minuti anche in presenza di cielo coperto.`,
  `Sfrutta la luce intensa del mattino per sopprimere immediatamente la melatonina e indurre un picco di cortisolo superiore al 50%.`,
  `Programma l'ora dell'esposizione alla luce mattutina per regolare l'inizio della produzione di melatonina previsto circa 12-14 ore dopo.`,
  `Elimina l'esposizione a luci intense e ad alta temperatura di colore (luce blu) nelle 2-3 ore precedenti il recarsi a dormire.`,
  `Utilizza esclusivamente luci calde e di bassa intensità nella fase serale per evitare il ritardo nel rilascio dell'ormone naturale.`,
  `Privilgia la luce naturale esterna rispetto a quella artificiale interna per garantire la corretta sincronizzazione dell'orologio biologico.`,
  `Assumere una dose giornaliera di 600 mg di estratto di radice di ashwagandha, suddivisa in due dosi da 300 mg ciascuna.`,
  `Continuare l'integrazione per un periodo minimo di 8 settimane per ottenere un aumento significativo del testosterone totale di circa 96 ng/dL.`,
  `Utilizzare l'ashwagandha per ridurre la percentuale di grasso corporeo, ottenendo una riduzione media del 3,5% superiore rispetto al non trattamento.`,
  `Integrare l'assunzione per massimizzare la crescita della forza muscolare durante un programma di allenamento di resistenza strutturato.`,
  `Migliorare il recupero post-allenamento riducendo il danno muscolare, mantenendo i livelli di creatina chinasi più stabili.`,
  `Sfruttare le proprietà adattogen own dell'estratto per abbassare i livelli di cortisolo e gestire la risposta del corpo allo stress fisico.`,
  `Assicurare l'utilizzo di un estratto di radice standardizzato per garantire l'efficacia clinica documentata nello studio.`,
  `Limitare la finestra alimentare giornaliera a un massimo di 6 ore totali).`,
  `Completare l'ultimo pasto della giornata entro le ore 15:00 per massimizzare la risposta circadiana.`,
  `Spostare l'assunzione calorica verso la prima metà della giornata per sfruttare la maggiore sensibilità insulinica naturale mattutina.`,
  `Concentrare l'apporto di carboidrati nelle ore del mattino per ottimizzare l'attività delle cellule beta pancreatiche.`,
  `Adottare una finestra alimentare anticipata per migliorare la pressione sanguigna e ridurre lo stress ossidativo anche senza ridurre il peso corporeo.`,
  `Evitare i pasti serali per ridurre la sensazione di fame e migliorare il controllo glicemico notturno.`,
  `Mantenere un apporto calorico di mantenimento per isolare i benefici metabolici derivanti esclusivamente dal tempismo dei pasti.`,
  `Assumere la combinazione di glicina e N-acetilcisteina per almeno 24 settimane per ripristinare i livelli di glutatione intracellulare nei soggetti sopra i 70 anni.`,
  `Utilizzare il protocollo GlyNAC per ridurre drasticamente lo stress ossidativo e i marcatori infiammzione sistemica tipici dell'età avanzata.`,
  `Implementare l'integrazione di GlyNAC per migliorare la funzione mitocondriale e ridurre il danno genomico nella popolazione anziana.`,
  `Sfruttare il trattamento con GlyNAC per ottimizzare l'insulino-resistenza e la funzione endoteliale attraverso il supporto al sistema antiossidante endogeno.`,
  `Supportare il mantenimento della forza muscolare, della velocità del cammino e delle funzioni cognitive tramite il trattamento prolungato con questi precursori.`,
  `Mantenere l'assunzione continuativa di GlyNAC, poiché i benefici fisiologici svaniscono entro 12 settimane dalla sospensione dell'esercizio.`,
  `Limitare l'uso dell'integrazione GlyNAC ai soggetti anziani o con alto stress ossidativo, poiché i giovani possiedono livelli di glutatione già ottimali.`,
  `Privilegia il mantenimento del glutatione nei giovani attraverso sonno di qualità qualità, esercizio fisico, consumo di verdure crucifere e un apporto proteico adeguato.`,
  `Adottare una frequenza respiratoria di circa 6 respiri al minuto per indurre la frequenza di risonanza del sistema cardiovascolare.`,
  `Mantenere un ritmo respiratorio costante di 0.1 Hz per massimizzare l'ampiezza della variabilità della frequenza cardiaca (HRV).`,
  `Eseguire cicli respiratori con inspirazione di 4-5 secondi ed espirazione di 5-6 secondi per attivare il sistema nervoso parasimpatico.`,
  `Praticare la respirazione lenta per almeno 5-10 minuti al giorno per aumentare la sensibilità dei barocettori arteriosi.`,
  `Utilizzare la tecnica della respirazione lenta come intervento immediato per ridurre l'attività del sistema simpatico e la pressione arteriosa.`,
  `Applicare la respirazione risonante prima di dormire per favorire il rilassamento profondo e il recupero fisiologico.`,
  `Impiegare la respirazione a 6 respiri al minuto come strumento di down-regulation durante le fasi di stress sotto carico di allenamento.`,
  `Esporre regolarmente la pelle ai raggi UVA per circa 30 minuti a mezzogiorno in giornate limpide per ridurre la pressione arteriosa sistemica.`,
  `Sfruttare l'esposizione solare per stimolare il rilascio di ossido nitrico cutaneo a favore della vasodilatazione arteriosa.`,
  `Considerare l'abbassamento della pressione tramite il sole come un meccanismo fisiologico distinto e indipendente dalla sintesi di vitamina D.`,
  `Aumentare l'esposizione ai raggi UV per abbassare la pressione sistolica indipendentemente dalle variazioni di temperatura ambientale.`,
  `Adottare un'esposizione solare moderata per ottenere benefici cardiovascolari senza raggiungere la soglia della scottatura o del danno oncologico cutaneo.`,
  `Utilizzare la luce solare come strumento non farmacologico per la gestione della salute vascolare oltre ai benefici del ritmo circadiano.`,
  `Monitorare i livelli di taurina nel sangue, poiché la loro concentrazione diminuisce naturalmente con l'avanzare dell'età nell'essere umano.`,
  `Assumere una dose giornaliera di taurina compresa tra 1 e 3 grammi per potenzialmente aumentare i processi di longevità, basandosi sui dati dei modelli preclinici.`,
  `Praticare regolarmente attività fisica di endurance acuta per stimolare naturalmente la produzione endogena di taurina.`,
  `Utilizzare l'apporto di taurina per contrastare i meccanismi di senescenza cellulare e disfunzione mitocondriale legati all'età.`,
  `Supportare la salute metabolica attraverso la taurina per ridurre lo stato di infammazione cronica di basso grado noto come inflammaging.`,
  `Integrare l'apporto di taurina per preservare l'integrità dei sistemi muscolare, osseo, cerebrale e immunitario nel lungo periodo.`,
  `Considerare la taurina come un'ipotesi terapeutica promettente, attendendo la conferma definitiva da trial clinici sull'uomo prima di certificarne l'efficacia anti-età.`,
  `Assumere urolitina A per attivare la mitofagia, ovvero il riciclo dei mitocondri danneggiati nel tessuto muscolare.`,
  `Integrare il composto per 4 mesi in adulti tra i 40 e i 65 anni per ottenere un incremento del 12% della forza muscolare.`,
  `Utilizzare l'urolitina A per migliorare l'endurance aerobica e la performance fisica misurata tramite test del cammino di 6 minuti.`,
  `Ridurre i livelli di acilcarnitine e di proteina C-reattiva per migliorare l'efficienza mitocondriale e l'infiammazione sistemica.`,
  `Somministrare il trattamento ai soggetti anziani per contrastare il declino della funzione muscolare legato all'invecchiamento naturale.`,
  `Ricorrere all'integrazione diretta di urolitina A poiché solo il 40% della popolazione è in grado di convertire gli ellagitannini alimentari nel metabolita attivo.`,
  `Privilelegiare il consumo di melograno, noci e frutti di bosco come fonti di precursori, pur essendo consape della variabilità della conversione intestinale individuale.`,
  `Privilegia l'uso di urolitina A per la longevità mitocondriale a lungo termine piuttosto che per guadagni di forza immediati nei soggetti giovani.`,
  `Assumere una dose giornaliera compresa tra i 1000 e i 1500 mg, suddivisa in 2 o 3 dosi da 500 mg ciascuna.`,
  `Somministrare l'integratore in corrispondenza dei pasti principali per massimizzare l'efficacia glicemica e il controllo del glucosio.`,
  `Utilizzare la berberina per ridurre significativamente la glicemia a digiuno, i livelli post-prandiali e l'emoglobina gliclicata (HbA1c).`,
  `Impiegare il protocollo per il trattamento della riduzione dei trigliceridi, del colesterolo totale e del colesterolo LDL.`,
  `Sfruttare l'attivazione dell'enzima AMPK per migliorare la sensibilità all'insulina e il metabolismo energetico cellulare.`,
  `Integrare la berberina esclusivamente come supporto e mai come sostituzione di una dieta bilanciata e di un'attività fisica regolare.`,
  `Monitorare eventuali effetti collaterali di natura gastrointestinali durante l'inizio del protocollo.`,
  `Consultare un medico prima dell'assunzione se si assumono farmaci, a causa dell'inibizione dell'enzima CYP450.`,
  `Assumere giornalmente almeno 500 mg di flavanoli contenuti nel cacao per migliorare le funzioni cognitive negli adulti sopra i 60 anni.`,
  `Garantire la presenza specifica di almeno 80 mg di epicatechina all'interno della dose per ottenere il supporto alla memoria dipendente dall'ippocampo.`,
  `Privilegia l'integrazione di flavanoli solo se la dieta di partenza è povera di polifenoli per massimizzare i benefici.`,
  `Mantenere il consumo costante di flavanoli per una durata di almeno un anno per consolidare i risultati sulla memoria nel tempo.`,
  `Scegliere cacao amaro o cioccolato fondente con percentuale di cacao superiore all'80% per garantire l'alto contenuto di flavanoli e ridurre gli zuccheri.`,
  `Integrare regolarmente nel piano alimentare frutti di bosco, mele e tè per aumentare l'apporto totale di polifenoli naturali.`,
  `Riconoscere che l'aggiunta di flavanoli è meno efficace in chi segue già una dieta abitualmente ricca di frutta e verdura.`,
  `Assumere 3 grammi di glicina circa 30-60 minuti prima di riposarsi per ridurre la latenza dell'addormentamento e la fatica diurna success.`,
  `Utilizzare la glicina per abbassare la temperatura corporea centrale, favorendo così il segnale biologico del sonno e l'efficienza del riposo.`,
  `Assumere tra i 200 e i 400 mg di magnesio sotto forma di bisglicinato o L-treonato per migliorare la qualità del sonno.`,
  `Scegliere il magnesio L-treonato per ottimizzare specificamente le fasi del sonno profondo e la fase REM.`,
  `Imministrare il magnesio bisglicinato per ridurre la severità dei sintomi dell'insonnia in un ciclo di assunzione di almeno 4 settimane.`,
  `Aumentare l'apporto di magnesio in presenza di stress elevato o di esercizio fisico regolare, fattori che ne incrementano il fabbisogno fisiologico.`,
  `Integrare l'uso di glicina e magnesio con l'igiene del sonno basata su buio totale e l'assenza di caffeina nel pomeriggio.`,
  `Assumere estratti standardizzati di Lion's Mane per garantire la presenza di erinacine ed ericenoni, composti attivi nella sintesi del fattore di crescita nervoso.`,
  `Utilizzare l'integratore per migliorare la velocità di elaborazione delle informazioni nel focus nei giovani adulti sani.`,
  `Integrare l'estratto di fungo nella routine per ridurre lo stress soggettivo e migliorare lo stato d'umore nel breve termine.`,
  `Monitorare i benefici cognitivi in soggetti con lieve declino, sapendo che i miglioramenti tendono a svanire dopo la sospensione dell'assunzione.`,
  `Considerare l'assunzione come un supporto sperimentale per il focus mentale piuttosto che come un nootropico con risultati garantiti nel tempo.`,
  `Adottare aspettative realistiche sull'efficacia, poiché l'evidenza clinica attuale è limitata da studi di piccola entità e durata.`,
  `Assumere regolarmente 180 mcg di menachinone-7 (MK-7) al giorno per ridurre la rigidità arteriosa nelle donne in postmenopausa.`,
  `Mantenere un apport giornaliero superiore a 32 mcg di vitamina K2 per ridurre del 50% il rischio di calcificazione arteriosa e complicazioni cardiovascolari.`,
  `Somministrare 360 mcg di MK-7 al giorno per un minimo 24 mesi per rallentare la progressione del calcio coronarico del 29 fino al 42%.`,
  `Utilizzare la vitamina K2 per attivare la proteina Matrix Gla (MGP), responsabile dell'inibizione attiva della deposizione di calcio nelle pareti delle arterie.`,
  `Integrare la vitamina K2 strategicamente con la vitamina D per garantire che il calcio assorbito venga indirizzato alle ossa anziché ai tessuti molli.`,
  `Privilegia il consumo di alimenti ricchi di K2 come il natto, i formaggi stagionati, il tuorlo d'uovo e il fegato per mantenere la salute vascolare.`,
  `Monitorare l'efficacia della Kazione specialmente nei soggetti che presentano già livelli elevati di rigidità arteriosa.`,
  `Consultare obbligatoriamente un medico prima di integrare vitamina K2 se si assumono farmaci anticoagulanti come il warfarin.`,
  `Il livello di consumo di alcol che minimizza i rischi per la salute è esclusivamente pari a zero unità.`,
  `Il rischio di mortalità per tutte le cause aumenta proporzionalmente anche a qualsiasi quantità di alcol consumata.`,
  `I presunti benefici cardiovascolari legati alle piccole dosi sono completamente compensati e superati dall'aumento del rischio di patologie neoplastic.`,
  `L'assunzione di alcol compromette gravemente la qualità del sonno alterando la pulizia glinfatica del cervello durante il riposo.`,
  `Il consumo di alcol riduce i livelli di testosterone e peggiora la composizione corporea totale.`,
  `Nella popolazione maschile compresa tra i 15 e i 49 anni, l'alcol è responsabile del 12% dei decessi.`,
  `Per massimizzare il recupero fisiologico è necessario ridurre sia la frequenza deie che la quantità di singola dose di alcol.`,
  `Somministrare una dose di caffeina compresa tra 3 e 6 mg per kg di peso corporeo tra 30 e 60 minuti prima dell'attività sportiva.`,
  `Utilizzare dosi inferiori tra 1 e 3 mg per kg di peso corporeo (equivalativamente 100-200 mg totale) per ottenere benefici ergogenici minimizzando effetti collaterali come tremori e tachicardia.`,
  `Adattare il dosaggio per un individuo di 86 kg assumendo tra 250 e 500 mg, oppure una dose più ridotta tra 100 e 250 mg.`,
  `Sfruttare l'inibizione dell'adenosina per ridurre la percezione soggettiva della fatica durante lo sforzo fisicoivo.`,
  `Evitare l'assunzione di caffeina oltre la metà giornata per prevenire alterazioni del sonno, data l'emivita di circa 5-6 ore.`,
  `Mantenere dosi moderate o programare cicli di assunzione per prevenire lo sviluppo di tolleranza che ridurrebbe l'efficacia della sostanza.`,
  `Utilizzare la caffeina specificamente per migliorare i parametri di forza, potenza, resistenza e la fatenza muscolare.`,
  `Eminminare per almeno 10 minuti immediatamente dopo ogni pasto per ridurre significativamente il picco glicemico.`,
  `Ridurre il valore della glicemia da circa 182 mg/dL a 164 mg/dL effettuando una breve attività invece di rimanere seduti.`,
  `Mantenere un passo di camminata costante di circa 3,8 km/h per ottenere i benefici metabolici necessari.`,
  `Privilegiare l'attività fisica immediata dopo la digestione rispetto a una passeggiata più lunga ma effettuata in seguito.`,
  `Sfruttare la contrazione muscolare per favorire l'assorbimento del glucosio in modo indipendente dall'insulina.`,
  `Dedicare una durata compresa tra i 10 e i 15 minuti al movimento dopo i pasti a più elevato contenuto di carboidrati.`,
  `Utilizzare la camminata post-prandiale per prevenire la sonnolenza dopo i pasti e migliorare il controllo metabolico a lungo termine.`,
  `Limitare il consumo di cibi ultra-processati per ridurre il rischio di mortalità per tutte le cause del 15%.`,
  `Adottare una strategia di dose-risposta riducendo la quantità di prodotti ultra-processati consumati proporzionalmente al rischio maggiore.`,
  `Sostituire sistematicamente gli snack confezionati e le bibite zuccherate con alimenti naturali per contrastare l'invecchiamento biologico accelerato.`,
  `Eliminare il consumo di carni lavorate e prodotti da forno di origine industriale dalla propria routine alimentare quotidiana.`,
  `Basare la dieta prevalentemente su cibi integri quali verdura, frutta, legumi e cereali integrali.`,
  `Sostituire i cibi pronti con additivi ed emulsionanti con carne, pesce, uova e latticini semplici.`,
  `Eseguire ogni possibile sostituzione di un prodotto ultra-processato con un alimento vero per migliorare la longevità.`,
  `Assumere 6-8 g di citrullina malato circa 60 minuti prima dell'allenamento per aumentare il volume di lavoro e il flusso sanguigno.`,
  `Assumere giornalmente tra 3 e 6 g di beta-alanina per un periodo minimo di 4 settimane per aumentare i livelli di carnosina muscolare del 30-60%.`,
  `Utilizzare la beta-alanina per migliorare la resistenza alla fatica in sforzi ad alta intensità della durata compresa tra i 30 secondi e i 10 minuti.`,
  `Frazionare la dose giornal giornaliera di beta-alanina durante la giornata per ridurre o eliminare l'effetto di parestesia (formicolio).`,
  `Sfruttare la citrullina malato per migliorare l'omeostasi dell'ammoniaca e favorire la vasodilatazione durante le sessioni di forza.`,
  `Pianificare l'integrazione di queste sostanze solo dopo aver stabilizzato i pilastri fondamentali di allenamento, apporto proteico, creatina e riposo.`,
  `Aspettarsi un incremento della performance del 2-3% circa negli atleti non elite grazie all'uso cronico di beta-alanina in sforzi intensi.`,
  `Mantenere legami sociali forti per ridurre il rischio relativo di mortalità del 50% rispetto a chi ne è privato.`,
  `Ridurre attivamente l'isolamento sociale per prevenire un aumento del rischio di mortalità del 29%.`,
  `Contrastare il senso di solitudine percepita per abbassare un rischio di decesso superiore al 26%.`,
  `Evitare di vivere da soli se possibile per limitare l'incremento del rischio del 32%.`,
  `Trattare la cura delle relazioni sociali come una priorità sanitaria, parabile per importanza al controllo dell'obesità e alla cessazione del fumo.`,
  `Scegliere l'allenamento fisico in gruppo per massimizzare simultaneamente i benefici del movimento e della connessione interpersonale.`,
  `Investire regolarmente nella costruzione di comunità e legami familiari come strategia concreta per prolungare la durata della vita.`,
  `Assumere curcumina in combinazione con piperina per aumentare la biodisponibilità del composto fino al 2000% entro 45 minuti.`,
  `Utilizzare l'integrazione di curcuminoidi per ridurre significativamente i marcatori infiammatori quali la proteina C-reattiva (CRP), l'interleuchina-6 (IL-6) e il fattore di necrosi tumorale alfa (TNF-alpha).`,
  `Consumare la curcumina in presenza di grassi per ottimizzarne l'assorbimento sistemico.`,
  `Sfruttare le proprietà della cumina per aumentare l'attività enzimatica della superossido dismutasi (SOD) e ridurre i livelli di malondialdeide (MDA).`,
  `Preferire formulazioni arricchite con piperina o tecnologie fitosomi per superare la scarsa biodisponibilità della curcumina di base.`,
  `Integrare l'uso della curcumina nel protocollo di gestione del dolore articolare e nelle fasi di infiammazione cronica.`,
  `Affiancare l'integrazione di curcumina a un controllo rigoroso del sonno, all'assunzione di omega-3 e dieta antinfiammatoria bilanciata.`,
  `Mantenere una durata del sonno ideale di circa 7 ore a notte per minimizzare il rischio relativo di mortalità generale.`,
  `Evitare di dormire meno di 7 ore notturne, poiché il rischio di decesso aumenta del 6% per ogni ora di deficitivo.`,
  `Limitare il sonno oltre le 7 ore notturne, poiché ogni eccesso cronico aumenta il rischio di mortalità del 13% per ora.`,
  `Targetizzare una finestra di riposo compresa tra le 7 e le 9 ore per garantire l'ottimale salute a lungo termine.`,
  `Non scendere il sonno sotto le 4 ore, condizione che porta il rischio relativo di mortalità fino a 1.55 rispetto al riferimento di 7 ore.`,
  `Privilegia la costanza degli orari di riposo per favorire la regolazione del testosterone, del recupero fisico e cognitivo.`,
  `Monitorare il sonno eccessivo cronico come potenziale segnale clinico di patologie sottostanti anziché come indicatore di salute.`,
  `Assumere una quantità giornaliera di fibra compresa tra 25 e 29 grammi per ridurre la mortalità per tutte le cause del 15-30%.`,
  `Mantenere un apporto minimo di almeno 25 grammi di fibra al giorno per abbattere significativamente il rischio di malattie cardiovascolari.`,
  `Incrementare l'assunzione di fibra oltre la soglia dei 29 grammi giornali per ottenere un ulteriore protezione della salute metabolica.`,
  `Privilegia il consumo di alimenti integri quali legumi, verdura, frutta, cereali integrali, noci e semi per raggiungere il fabbisogno totale.`,
  `Utilizzare l'apporto di fibre come strategia specifica per ridurre l'incidenza di ictus, diabete di tipo 2 e cancro al colon-retto.`,
  `Aumentare l'apporto di fibre in modo graduale per consentire il cor adattamento del sistema digerente.`,
  `Bere una quantità adeguata d'acqua in concomitanza con l'aumento delle fibre per favorire il corretto transito intestinale.`,
  `Sfruttare la funzione della fibra nel migliorare il controllo della glicemia e il senso di sazietà attraverso il nutrimento del microbioma.`,
  `Scegliere forme organiche legate ad acidi o aminoacidi anziché le forme inorganiche per massimizzare l'assorbimento cellulare.`,
  `Utilizzare il bisglicinato o il taurato di magnesio per ottenere la massima efficienza di assorbimento e tollerabilità intestinale.`,
  `Selezionare il magnesio citrato o malato come opzioni valide per un'elevata biodisponibilità.`,
  `Impiegare il magnesio L-treonato specificamente per supportare le funzioni cognitive e la qualità del sonno.`,
  `Evitare l'ossido di magnesio a causa della sua bassa biodisponibilità e della tendenza a causare effetti lassativi.`,
  `Somministrare una dose giornaliera compresa tra i 200 e i 400 mg di magnesio elementare.`,
  `Aumentare l'integrazione di magnesio in presenza di elevati livelli di stress o attività fisica prolungata.`,
  `Assumere 250 mg di NMN al giorno per un periodo compreso tra 6 e 12 settimane per aumentare i livelli ematici di NAD+ negli uomini anziani.`,
  `Utilizzare l'integrazione di NR o NMN per cicli di 14 giorni con loobiettivo di raddoppiare la concentrazione di NAD+ nel flusso sanguigno.`,
  `Privilegia l'integrazione di precursori del NAD+ esclusivamente nella popolazione in etàata, poiché i livelli di questo coenzima sono naturalmente elevati nei giovani.`,
  `Adottare l'esercizio fisico come strategia primaria e più solida per sostenere i livelli naturali di NAD+ nei soggetti di giovane età.`,
  `Privilegiare la qualità del sonno, l'allenamento e la dieta bilanciata rispetto all'uso di integratori di NMN o NR, attualmente costosi.`,
  `Considerare l'integrazione con NMN o NR come un approccio sperimentale, i cui i benefici clinici sull'invecchiamento nell'uomo non sono ancora confermati in modo definitivo.`,
  `Monitorare la funzione muscolare durante l'assunzione di NMN, poiché i dati clinici indicano alterazioni positive in questo ambito.`,
  `Aumentare l'assunzione dietetica di spermidina per stimolare il processo naturale di autofagia cellulare e il riciclo delle proteine dannegg.`,
  `Integrare regolarmente alimenti ricchi di spermidina nella dieta per ridurre il rischio di mortalità complessiva nel lungo periodo.`,
  `Prioritizzare il consumo di germe di grano come fonte alimentare principale e più concentrata di spermidina disponibile.`,
  `Consumare regolarmente prodotti di soia, natto e legumi per mantenere elevati livelli di poliammine nell'organismo.`,
  `Inserire funghi, formaggi stagionati, broccoli e mango nei pasti principali per supportare le funzioni di longevità.`,
  `Utilizzare l'assunzione di spermidina come strategia alimentare complementare al digiuno intermittente per massimizzare l'attivazione dell'autofagia.`,
  `Mantenere un'alta quota costante di spermidina per preservare gli effetti protettivi sulla salute, osservati negli studi di coorte di lunga durata.`,
  `Assumere succo di amarena Montmorency la sera per aumentare la durata totale del sonno di circa 34 minuti.`,
  `Consumare il succo di amarena per ridurre il tempo necessario all'addormentamento a letto di una media di 25 minuti.`,
  `Migliorare l'efficienza del sonno del 5-6% attraverso l'apporto naturale di melatonina e triptofano del frutto.`,
  `Utilizzare il'ratto per ridurre i marcatori del danno muscolare e i processi infiammatori dopo un esercizio fisico intenso.`,
  `Sfruttare gli antociani presenti nel frutto per accelerare i tempi di recupero muscolare e attenuire il dolore post-allenamento.`,
  `Prediligere il succo di amarena concentrato puro e diluito per evitare l'assunzione eccessiva di zuccheri aggiunti.`,
  `Programministre l'assunzione del succo specificamente durante i blocchi di allenamento ad alta intensità o nei periodi pre-gara.`,
  `Considerare il succo di amarena come un integratore complementare e non come sostituto delle buone abitudini fondamentali del sonno.`,
  `Consumare regolarmente tè verde o matcha per ridurre la massa corporea, l'indice di massa corporea e la percentuale di grasso.`,
  `Sfruttare l'epigallocchinina gallato (EGCG), che rappresenta tra il 48 e il 55% dei flavonoidi totali della bevanda.`,
  `Integrare il tè verde nella dieta per migliorare il profilo lipidico riducendo il colesterolo totale e il colesterolo LDL.`,
  `Utilizzare l'estratto di tè verde per aumentare i livelli di adiponectina e la capacità antiossidante dell'organismo.`,
  `Beneficiare della sinergia tra L-teanina e caffeina presente nel tè verde per migliorare il focus mentale e lo stato di calma.`,
  `Privilegiare sempre il consumo sotto forma di bevanda rispetto agli estratti concentrati ad alte dosi per prevenire il rischio di stress epatico.`,
  `Adottare il tè verde come supporto a una dieta bilanciata e all'attività fisica, poiché gli effetti metabolici sono più marcati in questo contesto.`,
  `Monitorare il consumo di catechine specialmente nei soggetti con sovrappeso o obesità per ottenere risultati metabolici più significativi.`,
  `Monitorare i livelli ematici di 25(OH)D per identificare eventuali carenze, specialmente sotto la soglia critica di 10 ng/ml.`,
  `Evitare la carenza grave di vitamina D per ridurre il rischio di mortalità, che nei casi di sepsi aumenta di un fatt di 1.92.`,
  `Privilegia l'integrazione di vitamina D per prevenire le infezioni respiratorie, soprattutto nei soggetti che presentano già un deficit di base.`,
  `Somministrare una dose giornaliera compresa tra 1000 e 2000 UI di vitamina D per correggere la carenza e mantenere livelli ematici adeguati.`,
  `Limitare l'uso di megadosi negli anziani che possiedono già livelli di vitamina D considerati sufficienti nel sangue.`,
  `Sostenere l'apporto di vitamina D attraverso l'esposizione al solare e il consumo regolare di pesce grasso.`,
  `Assumere la vitamina D in sinergia con la vitamina K2 per ottimizzarne il metabolismo e l'efficacia.`,
  `Concentarsi sulla correzione del deficit preesistente piuttosto che perseguire dosi massicce senza necessità clinica.`,
  `Iniziare l'assunzione di zinco entro le 24 ore dalla comparsa dei primi sintomi per massimizzare l'efficacia.`,
  `Utilizzare pastiglie di acetato di zinco da sciogliere in bocca per ottenere una riduzione della durata del raffreddore fino al 40%.`,
  `Applicare il gluconato di zinco per ridurre il decorso della malattia di circa il 28%.`,
  `Somministrare dosi elevate di zinco durante la fase acuta per accorciare i sintomi di media di 1,65 giorni.`,
  `Prediligere le forme farmaceutiche a rapido assorbimento orale per garantire il contatto diretto dello zinco con le mucose faringee.`,
  `Evitare l'assunzione cronica di alte dosi di zinco per prevenire interferenze negative con l'assorbimento del rame.`,
  `Mantenere uno stato di zinco adeguato tramite la dieta equilibrata per sostenere le funzioni immunitarie di base.`,
  `Limitare l'apporto di zucchero aggiunto al di sotto del 10% delle calorie giornaliere totali per minimizzare i rischi cardiovascolari.`,
  `Evitare il consumo di zucchero aggiunto superiore al 15% delle calorie giornaliere per prevenire un aumento dell'8% del rischio di malattia cardiovascolari totale.`,
  `Ridurre il consumo a meno di una porzione giornaliera di bevande zuccherate, poiché aumenta il rischio di eventi cardiovascolari del 29%.`,
  `Priorità all'eliminazione delle bevande zuccherate, come bibite, succhi ed energy drink, poiché lo zucchero liquido non favorisce il meccanismo della sazietà.`,
  `Sostituire sistemamente gli zuccheri liberi con la frutta intera per beneficiare della presenza di fibre che rallenta l'assorbimento.`,
  `Consumare i dolci in modo occasion all'interno di un pasto piuttosto che in modo isolato per mitigarne l'impatto metabolico.`,
  `Per l'atleta, privilegiare i carboidrati provenienti da fonti integrali e riservare quelli esclusivamente alla fase peri-workout.`,
  `Assumere bicarbonato di sodio per migliorare la performance in sforzi ad alta intensità della tra i 30 secondi e i 7 minuti.`,
  `Somministrare una dose giornalica compresa tra 0,2 e 0,3 grammi per chilogrammo di peso corporeo.`,
  `Programmare l'assunzione in un intervallo temporale comp tra 60 e 180 minuti prima dell'inizio della prova.`,
  `Frazionare la dose totale in più somministrazioni per minimizzare il rischio di disturbi gastrointestinali.`,
  `Assumere il bicarbonato insieme al pasto o utilizzare formulazioni a rivestimento enterico per migliorare la tollerabilità gastrica.`,
  `Utilizzare l'integrazione esclusivamente in sport con sforzi anaerobici ripetuti, come HIIT, arti marziali o sprint ripetuti.`,
  `Testare rigorosamente il protocollo di carico durante le sessioni di allenamento per evitare effetti collaterali imprevisti durante la gara.`,
  `Evitare l'uso del bicarbonato per attività di resistenza continua di tipo endurance, poiché il beneficio risulta scientificamente trascurabile.`,
  `Integrare l'uso del bicarbonato con la beta-alanina per ottenere un effetto tampone completo sia extracellulare che intracellulare.`,
  `Somministrare il Coenzima Q10 esclusivamente ai pazienti in terapia con statine che manifestano sintomi di more muscolare.`,
  `Utilizzare un dosaggio giornaliero compreso tra 100 mg e 200 mg di ubiquinolo per contrastare la riduzione dei livelli indotta dai farmaci.`,
  `Evitare l'integrazione di Coenzima Q10 in soggetti sani che non assumono statine, poiché non vi sono prove di benefici per l'energia generale.`,
  `Considerare il Coenzima Q10 come un intervento terapeutico mirato e non come un integratore energetico generico per la popolazione sana.`,
  `Privilegia l'potenziamento della funzione mitocondriale attraverso l'esercizio aerobico in Zona 2 rispetto all'uso di integratori.`,
  `Riconoscere il Coenzima Q10 come un cofattore essenziale della catena respiratoria per la produzione di ATP, la cui carenza è causata dalle statine.`,
  `Assumere creatina monoidrato con una dose compresa tra 5 e 10 grami al giorno per un periodo di almeno 4-8 settimane per migliorare l'umore.`,
  `Utilizzare la creatina come trattamento adiuvante alla terapia con antidepressivi SSRI o alla psicoterapia per potenziare i risultati clinici.`,
  `Sfruttare l'azione della creatina per ottimizzare il metabolismo energetico a livello cerebrale e fornire neuroprotettivo.`,
  `Mantenere un dosaggio giornaliero di circa 5 grami per supportare simultaneamente le funzioni muscolari, cognitive e ilumore.`,
  `Trattare l'integrazione di creatina come un supporto integrativo e mai come sostituzione delle terapie standard per la depressione clinica.`,
  `Impiegare la creatina per preservare le prestazioni cognitive specialmente in contesti di privazione del sonno.`,
  `Adottare un modello alimentare basato sull'uso quotidiano di olio extravergine d'oliva per ridurre del 30% il rischio di eventi cardiovascolari maggiori.`,
  `Integrare nel regime giornaliero una porzione di frutta secca (circa 30 grammi al giorno) come alternativa ai cibi a basso contenuto di grassi.`,
  `Privilegia il consumo di verdura e frutta come componenti fondamentali di ogni pasto per garantire l'apporto di fibre.`,
  `Consumare regolarmente legumi come fonte proteica principale, limitando drasticamente le proteine di origine.`,
  `Ridurre al minimo il consumo della carne rossa, delle carni lavorate e dei dolci zuccherati.`,
  `Focalizzarsi sulla qualità nutrizionale degli alimenti piuttosto che su una rigorosa restrizione calorica per ottenere benefici sulla protezione cardiovascolare.`,
  `Sostituire la carne con il pesce per aumentare l'apporto di acidi grassi omega-3.`,
  `Utilizzare cereali integrali come base della struttura alimentare per mantenere elevato il contenuto di micronutrienti.`,
  `Monitorare periodicamente i livelli di ferritina anziché la sola emoglobina, poiché la prima cala precocemente prima dell'insorgenza dell'anemia.`,
  `Valutare la presenza di carenza di ferro in presenza di fatica inspiegabile, calo della tolleranza all'esercizio, recupero lento o frequenti infezioni.`,
  `Prestare particolare attenzione alle atlete di endurance, poiché la prevalenza della carenza di ferro in questa categoria può raggiungere il 48% nelle maratonete competitive.`,
  `Compensare attivamente le perdite di ferro dovute al sudore, alle micro-emolisi da impatto meccanico del suolo e al ciclo mestruale nelle donne.`,
  `Aumentare l'apporto di ferro attraverso il consumo agevolato di carne rossa, fegato e legumi.`,
  `Abbiniare sempre le fonti di ferro vegetale con la vitamina C per massimizzare l'assorbimento del ferro non-eme.`,
  `Evitare l'integrazione di ferro senza una precisa documentazione medica clinica, poiché l'eccesso risulta dannoso per l'organismo.`,
  `Procedere all'integrazione terapeutica solo dopo aver confermato la carenza tramite esami del sangue specifici.`,
  `Assumere 100-200 mg di L-teanina per ogni 100 mg di caffeina per massimizzare l'attenzione selettiva e i tempi di reazione.`,
  `Mantenere un rapporto dosologico tra L-teanina e caffeina di circa 2:1 per ottenere un focus lucido senza nervosismo.`,
  `Utilizzare la combinazione dei due sostanze per contrastare i picchi pressori e l'ansia causati dal solo isolamento di caffeina.`,
  `Sfruttare la L-teanina per aumentare i livelli di GABA, serotonina e dopamina, favorendo così la concentrazione mentale sotto stress.`,
  `Applicare il protocollo L-teanina-caffeina per migliorare le prestazioni cognitive anche in presenza di comprovata privazione del sonno.`,
  `Privilegiare il tè verde o il matcha come fonti naturali di entrambi i composti necessari per il focus calmo.`,
  `Evitare l'assunzione di caffeina nelle ore tardive della giornata per non compromettere l'integrità del ciclo del sonno.`,
  `Assumere la melatonina tra 30 e 60 minuti prima dell'ora di coricarsi desiderata nella destinazione.`,
  `Utilizzare la melatonina specificamente per ridurre il jet lag nei viaggi che attraversano almeno 5 fusi orari.`,
  `Scegliere dosi comprese tra 0,5 mg e 1 mg per regolare efficacement il ritmo circadiano.`,
  `Administrare dosi tra 1 mg e 3 mg se l'obiettivo è facilitare l'addormentamento e migliorare la qualità del riposo.`,
  `Evitare dosi superiori ai 5 mg poiché non aumentano l'efficacia e possono causare eccessiva sonnolenza mattutina.`,
  `Privilegia la precisione del timing dell'assunzione rispetto all'ora bersaglio rispetto all'incremento del dosaggio.`,
  `Supportare l'azione della melatonina mantenendo un ambiente di totale buio e eliminando l'esposizione alla luce blu prima del sonno.`,
  `Utilizzare i probiotici come integrazione adiuvante alla terapia antidepressiva standard per massimizzare la riduzione dei sintomi depressivi.`,
  `Prediligere le formulazioni probiotiche multi-ceppo che combinano ceppi di Lactobacillus e Bifidobacterium rispetto all'uso di un ceppo singolo.`,
  `Adottare l'integrazione con psicobiotici per migliorare la risposta emotiva in soggetti sani sottoposti a stress elevato.`,
  `Incorrere regolarmente nel consumo di cibi fermentati naturali come yogurt con ferment, kefir e kimchi per sostenere la salute del microbioma.`,
  `Privilegia l'apporto adeguato di fibre per nutrire il microbioma e favorire la produzione di acidi grassi a catena corta necessari all'umore.`,
  `Considerare l'uso dei probiotici come un supporto moderato e mai come sostituzione totale dei trattamenti clinici per la depressione cronica.`,
  `Sfruttare l'asse intestino-cervello attraverso la modulazione della produzione di serotonina e GABA mediata dai batteri intestinali.`,
  `Assministrare una dose giornaliera di circa 30 mg di estratto standardizzato di zafferano per il trattamento della depressione lieve-moderata.`,
  `Utilizzare lo zafferano come alternativa naturale con efficacia paragonabile agli antidepressivi della classe SSRI per disturbi dell'umore non gravi.`,
  `Sfruttare lo zafferano per ridurre significativamente i punteggi di depressione misurati tramite Beck Scale.`,
  `Predilegere lo zafferano quando è necessario ridurre l'incidenza di eventi avversi del 6% rispetto ai farmaci antidepressivi tradizionali.`,
  `Limitare l'uso dello zafferano a casi di depressione e ansia lie o moderate, richiedendo consulenza medica per patologie cliniche gravi.`,
  `Adottare l'estratto di zafferano per la gestione dello stress e il miglioramento del tono dell'umore basato su evidenza scientifica.`,
  `Integrare obbligatoriamente la vitamina B12 nelle diete vegane e vegetariane poiché il nutriente è assente nei cibi di origine vegetale.`,
  `Monitorare i livelli di vitamina B12 e di omocisteina per identificare la causa primaria di stanchezza cronica e nebbia mentale.`,
  `Verificare la concentrazione di acido metilmalonico (MMA) per valutare la possibile disfunzione mitocondriale e la riduzione della produzione di energia neuronale.`,
  `Trattare la carenza di B12 per prevenire l'atrofia dell'ippocampo e il deterioramento delle funzioni cognitive superiori.`,
  `Ripristinare i livelli bassi di B12 per migliorare specificamente le prestazioni della memoria, le funzioni esecutive e la capacità di attenzione.`,
  `Evitare l'integrazione eccessiva di vitamina B12 in soggetti non carenti, poiché tale pratica non apporta benefici cognitivi aggiuntivi.`,
  `Prestare particolare attenzione ai soggetti anziani e a chi presenta patologie dell'assorbimento a causa del rischioato rischio di carenza.`,
  `Praticare la minimo 10 minuti al giorno di meditazione o di respirazione consapevole per ridurre i livelli di cortisolo ematico.`,
  `Adottare tecniche di respirazione lenta con una frequenza di circa 6 cicli al minuto per favorire la de-regolazione del sistema nervoso.`,
  `Utilizzare la mindfulness per aumentare l'attività della telomerasi, l'enzima responsabile della protezione dei telomeri.`,
  `Inserire le sessioni di meditazione come strumento complementare obbligatorio all'allenamento e al sonno per gestire il carico fisiologico.`,
  `Monitorare la regolarità quotidiana per massimizzare la lunghezza dei telomeri e contrastare i processi di invecchiamento cellulare.`,
  `Sfruttare le tecniche di mindfulness per abbassare significativamente i livelli di ansia e lo stress percepito.`,
  `Trascorrere tempo in ambiente boschivo per aumentare significativamente il numero e l'attività delle cellule Natural Killer.`,
  `Mantenere il potenziale immunitario derivante dall'esposizione forestale per fino a 7 giorni dopo il termine dell'attività.`,
  `Praticare l'immersione nella natura per ridurre i livelli di cortisolo nel sangue e l'adrenalina nelle urine.`,
  `Favorire lo spostamento del sistema nervoso verso la dominanza parasimpatica attraverso il rilassamento in contesti naturaliati.`,
  `Inalare attivamente i composti volatili fitoncidi rilasciati dagli alberi per stimolare la risposta anti-virus e anti-stress.`,
  `Eseguire camminate lente e respirare profondamente nei parchi verdi per massimizzare i benefici fisiologici.`,
  `Utilizzare l'attività forestale come strumento di recupero attivo combinando movimento, luce mattutina e deconnessione tecnologica.`,
  `Utilizzare l'esercizio fisico come trattamento primario per forme di depressione e ansia di grado lieve o moderate, raggiungendo efficacia comparabile a degli antidepressivi.`,
  `Privilegia l'allenamento aerobico ad alta intensità (HIIT) per massimizzare la produzione del fattore neurotrofico derivato dal cervello BDNF.`,
  `Eseguire sessioni di attività fisica regolari per regolare l'asse dello stress (HPA) e ridurre i livelli di infiammazione sistemica.`,
  `Integrare regolarmente discipline mente-corpo, come lo yoga o il tai chi, per ottenere una riduzione significativa dei sintomi ansiosi e depressivi.`,
  `Strutturare un programma di allenamento costante che combini esercizi di forza e sessioni aerobiche di media intensità per proteggere la salute mentale a lungo termine.`,
  `Adottare l'attività fisica come alleato terapeutico fondamentale accanto alle cure farmacologiche, sfruttando l'assenza di effetti collaterali negativi tipici dei farmaci.`,
  `Privilegia gli integratori di omega-3 ricchi di acido eicosapentaenoico (EPA) rispetto al DHA per la gestione dei sintomi depressivi.`,
  `Selezionare formulazioni con una concentrazione di EPA pari o superiore al 60% del totale degli acidi grassi.`,
  `Somministrare un dosaggio giornaliero di circa 1 gramo di EPA puro per ottenere il massimo beneficio clinicoico.`,
  `Utilizzare l'integrazione di EPA prevalentemente come terapia adiuvante in presenza di trattamento farmacologico antidepressivo già in corso.`,
  `Evitare l'uso di soli basati esclusivamente sul DHA se l'obiettivo primario è il miglioramento dello stato dell'umore.`,
  `Considerare l'assunzione di EPA come un supporto e non come un sostituto dei protocolli terapeutici standard per la depressione clinica.`,
  `Assumere un estratto standardizzato di Rhodiola rosea SHR-5 in dosi comprese tra 288 e 680 mg al giorno.`,
  `Somministrare l'integratore al mattino per massimizzare l'effetto sulla performance cognitiva e sull'umore.`,
  `Proseguire il trattamento per una durata variabile da 2 a 6 settimane per ottenere benefici significativi sulla riduzione della fatica.`,
  `Utilizzare il dosaggio specifico di 576 mg al giorno per ridurre i sintomi del burnout e normalizzare la risposta del cortisolo al risveglio.`,
  `Integrare l'uso durante i periodi di lavoro notturno o durante le fasi di sovrallenamento fisico.`,
  `Adottare un'assunzione a cicli anziché in modo continuo per mantenere l'efficacia dell'adattogeno.`,
  `Considerare la Rhodiola come supporto funzionale senza mai sostituire il riposo notturno o la gestione del carico di lavoro.`,
];

export const KNOWLEDGE_SOURCES = [
  { title: `alcol nessun livello sicuro`, topic: ``, principles: 0 },
  { title: `allenamento forza dose mortalita`, topic: ``, principles: 0 },
  { title: `ashwagandha testosterone forza giovani`, topic: ``, principles: 0 },
  { title: `berberina glucosio metabolismo`, topic: ``, principles: 0 },
  { title: `cacao flavanoli cervello memoria`, topic: ``, principles: 0 },
  { title: `caffeina performance ergogenica`, topic: ``, principles: 0 },
  { title: `caffeina timing sonno`, topic: ``, principles: 0 },
  { title: `camminata post pasto glicemia`, topic: ``, principles: 0 },
  { title: `cibi fermentati microbioma infiammazione`, topic: ``, principles: 0 },
  { title: `cibi ultraprocessati mortalita`, topic: ``, principles: 0 },
  { title: `citrullina beta alanina performance`, topic: ``, principles: 0 },
  { title: `connessioni sociali mortalita`, topic: ``, principles: 0 },
  { title: `creatina anziani forza massa`, topic: ``, principles: 0 },
  { title: `creatina cervello cognizione sonno`, topic: ``, principles: 0 },
  { title: `curcumina piperina infiammazione`, topic: ``, principles: 0 },
  { title: `digiuno 16 8 allenamento forza`, topic: ``, principles: 0 },
  { title: `digiuno anticipato etrf insulina`, topic: ``, principles: 0 },
  { title: `durata sonno mortalita`, topic: ``, principles: 0 },
  { title: `esercizio nutrizione longevita`, topic: ``, principles: 0 },
  { title: `fibra mortalita`, topic: ``, principles: 0 },
  { title: `fitness cardiorespiratoria vs peso mortalita`, topic: ``, principles: 0 },
  { title: `fitness vo2max mortalita nessun tetto`, topic: ``, principles: 0 },
  { title: `forza presa mano biomarcatore mortalita`, topic: ``, principles: 0 },
  { title: `freddo immersione dopamina noradrenalina`, topic: ``, principles: 0 },
  { title: `gelatina vitamina c tendini collagene`, topic: ``, principles: 0 },
  { title: `glicina magnesio sonno`, topic: ``, principles: 0 },
  { title: `glynac glutatione mitocondri`, topic: ``, principles: 0 },
  { title: `lions mane cognizione ngf`, topic: ``, principles: 0 },
  { title: `luce mattutina circadiano cortisolo melatonina`, topic: ``, principles: 0 },
  { title: `magnesio forme biodisponibilita`, topic: ``, principles: 0 },
  { title: `microbioma intestinale sonno`, topic: ``, principles: 0 },
  { title: `nitrati barbabietola pressione`, topic: ``, principles: 0 },
  { title: `nmn nad invecchiamento`, topic: ``, principles: 0 },
  { title: `omega3 sintesi proteica recupero`, topic: ``, principles: 0 },
  { title: `proteine per pasto leucina sintesi muscolare`, topic: ``, principles: 0 },
  { title: `respirazione lenta hrv pressione`, topic: ``, principles: 0 },
  { title: `sauna mortalita cardiovascolare`, topic: ``, principles: 0 },
  { title: `sistema glinfatico sonno pulizia cervello`, topic: ``, principles: 0 },
  { title: `sole ossido nitrico pressione`, topic: ``, principles: 0 },
  { title: `sonno testosterone uomini giovani`, topic: ``, principles: 0 },
  { title: `spermidina autofagia longevita`, topic: ``, principles: 0 },
  { title: `succo amarena sonno recupero`, topic: ``, principles: 0 },
  { title: `sulforafano germogli broccoli nrf2`, topic: ``, principles: 0 },
  { title: `taurina invecchiamento`, topic: ``, principles: 0 },
  { title: `te verde catechine metabolismo`, topic: ``, principles: 0 },
  { title: `urolitina a mitofagia muscolo`, topic: ``, principles: 0 },
  { title: `vitamina d mortalita immunita`, topic: ``, principles: 0 },
  { title: `vitamina k2 arterie calcificazione`, topic: ``, principles: 0 },
  { title: `zinco raffreddore immunita`, topic: ``, principles: 0 },
  { title: `zone2 lattato mitocondri san millan`, topic: ``, principles: 0 },
  { title: `zucchero aggiunto cardiovascolare`, topic: ``, principles: 0 },
  { title: `bicarbonato sodio performance`, topic: `Bicarbonato di sodio per la performance `, principles: 9 },
  { title: `coq10 statine energia`, topic: `Coenzima Q10 e miopatia da statine`, principles: 6 },
  { title: `creatina umore depressione`, topic: `Creatina nel trattamento dell'umore e de`, principles: 6 },
  { title: `dieta mediterranea predimed`, topic: `Prevenzione cardiovascolare tramite la d`, principles: 8 },
  { title: `ferro carenza fatica`, topic: `Carenza di ferro e performance negli spo`, principles: 8 },
  { title: `l teanina caffeina focus`, topic: `Sinergia L-teanina e caffeina per le pre`, principles: 7 },
  { title: `melatonina sonno jetlag`, topic: `Melatonina per la gestione del jet lag e`, principles: 7 },
  { title: `probiotici umore depressione`, topic: `Probiotici e gestione dell'umore/depress`, principles: 7 },
  { title: `zafferano depressione`, topic: `Zafferano nel trattamento della depressi`, principles: 6 },
  { title: `b12 cognizione energia`, topic: `Vitamina B12, funzioni cognitive e produ`, principles: 7 },
  { title: `mindfulness cortisolo telomeri`, topic: `Mindfulness e gestione cellulare dello s`, principles: 6 },
  { title: `natura foresta stress immunita`, topic: `Effetti del forest bathing sulla salute `, principles: 7 },
  { title: `esercizio depressione ansia`, topic: `Esercizio fisico nel trattamento di depr`, principles: 6 },
  { title: `omega3 epa depressione`, topic: `Efficacia degli omega-3 EPA nel trattame`, principles: 6 },
  { title: `rodiola fatica stress`, topic: `Rhodiola rosea per la gestione della fat`, principles: 7 },
];

const _HEADER = "\n\nPRINCIPI SCIENTIFICI (distillati da paper reali — fonda i consigli su questi e citali quando pertinenti):\n";
const _norm = (s) => String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
const _STOP = new Set(['della','dello','degli','delle','come','dopo','prima','molto','anche','essere','perche','quando','quanto','sono','hanno','con','per','che','non','una','uno','gli','dei','del','nel','nella','sul','più','meno','cosa','dove','fare','puoi','devo','vorrei','meglio','aiuto','consiglio','consigli']);
function _wrap(list, max) {
  let body = list.map((p, i) => `${i + 1}. ${p}`).join('\n');
  if (body.length > max) body = body.slice(0, max).replace(/\n[^\n]*$/, '') + '\n…';
  return _HEADER + body;
}

// Iniezione "statica": i primi N principi (fallback / nessuna query).
export function knowledgePrompt(max = 3500) {
  if (!Array.isArray(NUTRITION_PRINCIPLES) || !NUTRITION_PRINCIPLES.length) return '';
  return _wrap(NUTRITION_PRINCIPLES, max);
}

// Iniezione "per pertinenza": classifica i principi in base alla domanda/contesto
// e inietta i più rilevanti. Ribalta il sistema da "primi N" a "i N che servono".
export function knowledgePromptFor(query, max = 2600) {
  if (!Array.isArray(NUTRITION_PRINCIPLES) || !NUTRITION_PRINCIPLES.length) return '';
  const terms = [...new Set(_norm(query || '').split(/[^a-z0-9]+/).filter((w) => w.length >= 4 && !_STOP.has(w)))];
  if (!terms.length) return _wrap(NUTRITION_PRINCIPLES, max);
  const scored = NUTRITION_PRINCIPLES.map((p, i) => {
    const n = _norm(p);
    // match per radice: confronta il prefisso (6 char) → "stressato" aggancia "stress"
    let s = 0; for (const t of terms) if (n.includes(t.slice(0, 6))) s++;
    return { p, i, s };
  });
  const hits = scored.filter((x) => x.s > 0).sort((a, b) => b.s - a.s || a.i - b.i).map((x) => x.p);
  // se pochi match, completa con i principi generali (in ordine) fino al budget
  const rest = scored.filter((x) => x.s === 0).map((x) => x.p);
  const ordered = [...hits, ...rest];
  return _wrap(ordered, max);
}
