// ─────────────────────────────────────────────────────────────────────────────
//  Scheletro del curriculum di Polacco: solo i TEMI (zero token, zero I/O).
//  Fonte UNICA condivisa da app web (src/pages/Polish.jsx) e bot Telegram
//  (api/telegram/webhook.js) — stesso pattern di lib/frenchCurriculum.js.
// ─────────────────────────────────────────────────────────────────────────────

export const PL_CURRICULUM = [
  { level: 'A1', color: '#c4423b', units: [
    { id: 'a1-01', emoji: '👋', title: 'Saluti e presentazioni', topic: 'saluti (cześć, dzień dobry), presentarsi, come stai, di dove sei' },
    { id: 'a1-02', emoji: '🔢', title: 'Numeri 0–20', topic: 'numeri da 0 a 20, contare, età' },
    { id: 'a1-03', emoji: '🗓️', title: 'Giorni e mesi', topic: 'giorni della settimana, mesi, che giorno è' },
    { id: 'a1-04', emoji: '👨‍👩‍👧', title: 'La famiglia', topic: 'membri della famiglia, aggettivi possessivi mój/moja/moje' },
    { id: 'a1-05', emoji: '🧍', title: 'Verbo być (essere)', topic: 'coniugazione presente di być, frasi semplici (jestem, jesteś, jest)' },
    { id: 'a1-06', emoji: '🎒', title: 'Verbo mieć (avere)', topic: 'coniugazione presente di mieć, possesso (mam, masz, ma)' },
    { id: 'a1-07', emoji: '⚧️', title: 'I tre generi', topic: 'maschile/femminile/neutro, terminazioni tipiche dei nomi' },
    { id: 'a1-08', emoji: '🍎', title: 'Al bar e al ristorante', topic: 'ordinare cibo e bevande, poproszę, chiedere il conto' },
    { id: 'a1-09', emoji: '🎨', title: 'Colori e oggetti', topic: 'colori, oggetti comuni, to jest / to są' },
    { id: 'a1-10', emoji: '🕐', title: 'Orari e appuntamenti', topic: 'chiedere l\'ora, orari di apertura, fissare un appuntamento' },
    { id: 'a1-11', emoji: '🏠', title: 'Hotel e alloggio', topic: 'prenotare una camera, check-in, chiedere servizi in hotel' },
    { id: 'a1-12', emoji: '🛒', title: 'Shopping e necessità', topic: 'negozi, taglie, prezzi, pagare, chiedere aiuto' },
    { id: 'a1-13', emoji: '🚫', title: 'La negazione', topic: 'nie davanti al verbo, forme negative comuni' },
    { id: 'a1-14', emoji: '🧑‍🎨', title: 'Aggettivi qualificativi', topic: 'accordo di genere degli aggettivi, descrivere persone e cose' },
    { id: 'a1-15', emoji: '🛋️', title: 'La casa e le stanze', topic: 'stanze della casa, mobili, preposizioni di luogo (w, na)' },
    { id: 'a1-16', emoji: '🧭', title: 'Chiedere indicazioni', topic: 'indicazioni per strada, prosto, w lewo/w prawo' },
    { id: 'a1-17', emoji: '⚡', title: 'Verbi in -ować', topic: 'presente dei verbi in -ować (pracować, kupować), coniugazione tipica' },
    { id: 'a1-18', emoji: '🍽️', title: 'Al mercato', topic: 'cibo, quantità (dużo/mało), fare la spesa' },
    { id: 'a1-19', emoji: '🐶', title: 'Animali e natura', topic: 'animali comuni, la campagna, gusti e preferenze (lubię)' },
    { id: 'a1-20', emoji: '📱', title: 'Telefono e tecnologia', topic: 'rispondere al telefono, messaggi, vocabolario tech di base' },
  ] },
  { level: 'A2', color: '#c47a3b', units: [
    { id: 'a2-01', emoji: '🚆', title: 'Muoversi in viaggio', topic: 'stazione e aeroporto, biglietti, coincidenze, imprevisti' },
    { id: 'a2-02', emoji: '🔤', title: 'Il caso Biernik (accusativo)', topic: 'caso accusativo per il complemento oggetto, prime declinazioni' },
    { id: 'a2-03', emoji: '🕰️', title: 'Il passato', topic: 'passato dei verbi (forma in -łem/-łam), raccontare cosa hai fatto' },
    { id: 'a2-04', emoji: '🌤️', title: 'Il tempo e le stagioni', topic: 'meteo, stagioni, jest zimno/ciepło' },
    { id: 'a2-05', emoji: '💼', title: 'Lavoro e professioni', topic: 'professioni, descrivere il proprio lavoro' },
    { id: 'a2-06', emoji: '🩺', title: 'Salute in viaggio', topic: 'spiegare sintomi, farmacia, medico, boli mnie...' },
    { id: 'a2-07', emoji: '🎭', title: 'Tempo libero', topic: 'hobby, lubię + infinito, uscite' },
    { id: 'a2-08', emoji: '➡️', title: 'Il futuro', topic: 'futuro dei verbi imperfettivi (będę + infinito), progetti' },
    { id: 'a2-09', emoji: '🔁', title: 'Aspetto verbale: intro', topic: 'differenza tra verbi imperfettivi e perfettivi, idea di base' },
    { id: 'a2-10', emoji: '⚖️', title: 'Comparativi e superlativi', topic: 'bardziej/najbardziej, confrontare cose' },
    { id: 'a2-11', emoji: '❗', title: 'L\'imperativo', topic: 'imperativo affermativo e negativo, dare istruzioni e consigli' },
    { id: 'a2-12', emoji: '🏙️', title: 'La città e il quartiere', topic: 'edifici pubblici, mezzi di trasporto urbani, orientarsi' },
    { id: 'a2-13', emoji: '🎉', title: 'Feste e tradizioni', topic: 'festività polacche, auguri, inviti ed eventi' },
    { id: 'a2-14', emoji: '✉️', title: 'Scrivere un messaggio', topic: 'registro formale/informale, formule di apertura e chiusura' },
    { id: 'a2-15', emoji: '👥', title: 'Pronomi e forme di cortesia', topic: 'ja/ty/on/ona, pan/pani nelle frasi, evitare "ty" con sconosciuti' },
    { id: 'a2-16', emoji: '🔢', title: 'Numeri oltre il 20 e ordinali', topic: 'numeri grandi, pierwszy/drugi/trzeci, date' },
  ] },
  { level: 'B1', color: '#7c5cc4', units: [
    { id: 'b1-01', emoji: '📖', title: 'Raccontare storie', topic: 'aspetto perfettivo vs imperfettivo al passato, narrare eventi' },
    { id: 'b1-02', emoji: '🎯', title: 'Obiettivi e desideri', topic: 'condizionale (chciałbym/chciałabym), ipotesi' },
    { id: 'b1-03', emoji: '🧩', title: 'Il caso Celownik (dativo)', topic: 'caso dativo per il destinatario, pronomi mi/ci/mu' },
    { id: 'b1-04', emoji: '🌍', title: 'Attualità e società', topic: 'temi di attualità, argomentare, connettori' },
    { id: 'b1-05', emoji: '🎬', title: 'Cultura polacca', topic: 'cinema, musica, abitudini culturali polacche' },
    { id: 'b1-06', emoji: '🔧', title: 'Il caso Narzędnik (strumentale)', topic: 'caso strumentale per il mezzo/compagnia, jechać czym' },
    { id: 'b1-07', emoji: '🗣️', title: 'Opinioni', topic: 'esprimere opinioni, myślę że, uważam że' },
    { id: 'b1-08', emoji: '🔗', title: 'Connettori logici', topic: 'jednak, więc, dlatego, strutturare un discorso' },
    { id: 'b1-09', emoji: '🧑‍💼', title: 'Il colloquio di lavoro', topic: 'CV, punti di forza, rispondere a domande di colloquio' },
    { id: 'b1-10', emoji: '✈️', title: 'Viaggiare in modo sostenibile', topic: 'ambiente, trasporti alternativi, esprimere preoccupazioni' },
    { id: 'b1-11', emoji: '🗳️', title: 'Dibattere un\'opinione', topic: 'z jednej strony...z drugiej, essere d\'accordo/in disaccordo con sfumature' },
    { id: 'b1-12', emoji: '🏛️', title: 'Storia e geografia polacca', topic: 'regioni della Polonia, eventi storici principali, piccoli aneddoti' },
    { id: 'b1-13', emoji: '🔮', title: 'Il futuro perfettivo', topic: 'futuro dei verbi perfettivi (forma semplice, senza będę), differenza con l\'imperfettivo' },
    { id: 'b1-14', emoji: '🍲', title: 'Cucina e ricette', topic: 'ingredienti, istruzioni con l\'imperativo, piatti tipici polacchi' },
  ] },
  { level: 'B2', color: '#3bc4a0', units: [
    { id: 'b2-01', emoji: '🎓', title: 'Il caso Miejscownik (locativo)', topic: 'caso locativo dopo preposizioni w/na/o, sfumature d\'uso' },
    { id: 'b2-02', emoji: '🎭', title: 'Registro formale vs informale', topic: 'ty/pan/pani, differenze di registro, linguaggio colloquiale' },
    { id: 'b2-03', emoji: '📝', title: 'Argomentare per iscritto', topic: 'struttura di un breve testo argomentativo, connettori avanzati' },
    { id: 'b2-04', emoji: '📚', title: 'Letteratura polacca', topic: 'autori celebri, estratti semplificati, commentare un testo' },
    { id: 'b2-05', emoji: '🤝', title: 'Negoziare e persuadere', topic: 'linguaggio della negoziazione, proporre e controproporre' },
    { id: 'b2-06', emoji: '🗿', title: 'Espressioni idiomatiche', topic: 'modi di dire polacchi comuni e il loro uso naturale' },
    { id: 'b2-07', emoji: '⏳', title: 'Aspetto verbale avanzato', topic: 'coppie aspettuali meno regolari, sfumature d\'uso perfettivo/imperfettivo' },
    { id: 'b2-08', emoji: '🎤', title: 'Presentazioni orali', topic: 'struttura di una presentazione, gestire domande del pubblico' },
    { id: 'b2-09', emoji: '⏳', title: 'Tutti i casi insieme', topic: 'ripasso e confronto dei 7 casi (mianownik→miejscownik/wołacz), tabella pratica' },
    { id: 'b2-10', emoji: '🧠', title: 'Il condizionale passato', topic: 'gdybym wiedział/wiedziała, rimpianti e ipotesi non realizzate' },
  ] },
  { level: 'C1', color: '#3bc4a0', units: [
    { id: 'c1-01', emoji: '🏗️', title: 'Il caso Dopełniacz (genitivo)', topic: 'caso genitivo dopo negazione e quantità, l\'uso più complesso dei 7 casi' },
    { id: 'c1-02', emoji: '🎨', title: 'Stile ed enfasi', topic: 'ordine delle parole flessibile, mettere in rilievo un\'informazione' },
    { id: 'c1-03', emoji: '📰', title: 'Comprendere la stampa', topic: 'lessico giornalistico, titoli, sintetizzare un articolo' },
    { id: 'c1-04', emoji: '⚖️', title: 'Diritto e istituzioni', topic: 'sistema politico polacco, vocabolario legale di base' },
    { id: 'c1-05', emoji: '🧬', title: 'Scienza e tecnologia', topic: 'lessico scientifico, spiegare un concetto tecnico in modo semplice' },
    { id: 'c1-06', emoji: '🎭', title: 'Ironia e sfumature', topic: 'sarcasmo, understatement, capire il non detto' },
    { id: 'c1-07', emoji: '🗣️', title: 'Dialetti e varietà regionali', topic: 'differenze regionali, gwara śląska/kaszubska, espressioni locali' },
    { id: 'c1-08', emoji: '📊', title: 'Presentare dati', topic: 'descrivere grafici e tendenze, vocabolario di analisi' },
    { id: 'c1-09', emoji: '🤔', title: 'Dilemmi etici', topic: 'discutere questioni morali complesse, pesare pro e contro con sfumature' },
    { id: 'c1-10', emoji: '🖋️', title: 'Scrittura creativa', topic: 'descrivere scene ed emozioni con un registro letterario' },
  ] },
];

export const PL_ALL_UNITS = PL_CURRICULUM.flatMap((l) => l.units.map((u) => ({ ...u, level: l.level, color: l.color })));
export const plUnitById = (id) => PL_ALL_UNITS.find((u) => u.id === id);
export const plUnitByIndex = (idx) => PL_ALL_UNITS[Math.max(0, Math.min(PL_ALL_UNITS.length - 1, idx || 0))];
