// ─────────────────────────────────────────────────────────────────────────────
//  NOVITÀ DAGLI STUDI — highlight curati a mano dai paper distillati.
//  A differenza di lib/knowledgeBase.js (auto-generato e sovrascritto dai tool),
//  questo file è editoriale: le "perle" più sorprendenti selezionate per la UI.
//  Ogni vota la ricerca notturna trova qualcosa di forte, si aggiunge qui una card.
// ─────────────────────────────────────────────────────────────────────────────

// cat: chiave categoria · icona/colore vivono in SCIENCE_CATEGORIES qui sotto.
// punch: il titolo-gancio (ciò che sorprende). detail: la sfumatura/come applicarlo.
// myth: true = sfata una credenza comune (badge speciale). fresh: false = ultima tornata.
export const SCIENCE_HIGHLIGHTS = [
  { id: 'caffeina-90min', cat: 'sonno', emoji: '☕', punch: 'Aspetta 90 minuti prima del primo caffè', detail: 'Il cortisolo naturale sale già del 50-75% nei primi 30-45 min dal risveglio. Ritardare la caffeina evita la sovrapposizione e riduce il crollo di metà mattina.', tag: 'Risveglio', fresh: false },
  { id: 'snooze-ok', cat: 'sonno', emoji: '⏰', punch: 'Lo snooze non è il nemico che credi', detail: 'Uno studio di Stoccolma (2023) mostra che 30 min di snooze non danneggiano il sonno e possono ridurre l\'inerzia del risveglio. Basta non abusarne: una volta sola.', tag: 'Risveglio', myth: true, fresh: false },
  { id: 'coffee-nap', cat: 'energia', emoji: '⚡', punch: 'Il "coffee nap" batte caffè e pisolino presi da soli', detail: 'Caffè + pisolino di 15-20 minuti insieme: la caffeina fa effetto proprio mentre ti svegli, sommando i due benefici. Vigilanza superiore a ciascuno separato.', tag: 'Energia', fresh: false },
  { id: 'adrenal-fatigue', cat: 'energia', emoji: '🚫', punch: '"Fatica surrenale": non esiste', detail: '58 studi la smontano: non c\'è evidenza che le surrenali si "esauriscano". La stanchezza cronica ha cause reali (sonno, ferro, tiroide, ME/CFS) da indagare, non un mito da integrare.', tag: 'Energia', myth: true, fresh: false },
  { id: 'butirrato', cat: 'intestino', emoji: '🦠', punch: 'Il butirrato spegne l\'infiammazione dall\'interno', detail: 'È il 20% degli acidi grassi a catena corta prodotti dai batteri: rinforza le tight junction intestinali e attiva i linfociti T regolatori. Lo nutri con fibre fermentabili (inulina, psillio, avena).', tag: 'Microbiota', fresh: false },
  { id: 'mediterranea-il6', cat: 'cibo', emoji: '🫒', punch: 'La dieta mediterranea abbassa IL-6 e CRP del 30%+', detail: 'Meta-analisi su 33 RCT (3.476 persone). E qui il dato forte: sul marcatore infiammatorio l\'intervento dietetico batte l\'esercizio da solo. Olio EVO come moltiplicatore.', tag: 'Anti-infiammazione', fresh: false },
  { id: 'mindfulness-cortisolo', cat: 'mente', emoji: '🧘', punch: '10-20 min di mindfulness abbassano il cortisolo misurato', detail: 'Meta-analisi su 35 trial: 25 mostrano cortisolo ridotto, 10 nessun effetto. Funziona, ma effetto piccolo-medio: rende di più abbinata a sonno ed esercizio.', tag: 'Stress', fresh: false },
  { id: 'cold-water', cat: 'allenamento', emoji: '🧊', punch: 'Acqua fredda: 10-15 min a 11-15°C è il punto ottimale', detail: 'Network meta-analisi 2025: quella finestra è la migliore per il dolore muscolare (DOMS), abbassa la creatina chinasi e migliora il salto. Più freddo di così = solo più scomodo.', tag: 'Recupero', fresh: false },
  { id: 'magnesio', cat: 'integratori', emoji: '💊', punch: 'Il magnesio lavora su sonno, muscoli e cuore insieme', detail: 'Blocca il calcio in eccesso nei neuroni: meno crampi, sonno più profondo. Carenza lieve legata a ipertensione e aritmie. Meglio glicinato/treonato, 300-400 mg la sera.', tag: 'Minerali', fresh: false },
  { id: 'creatina-anziani', cat: 'integratori', emoji: '🏋️', punch: 'La creatina fa guadagnare muscolo anche a 80 anni', detail: '3-5 g/die (niente fase di carico) + allenamento coi pesi: aumenta massa magra e forza pure in età avanzata. Uno dei 5-6 integratori con evidenza "alta" secondo l\'ISSN.', tag: 'Integratori', fresh: false },
  { id: 'vo2max', cat: 'longevita', emoji: '🫀', punch: 'Il VO2max predice la longevità meglio di quasi tutto', detail: 'Chi è nel gruppo "elite" di fitness ha ~5 volte meno mortalità del gruppo meno allenato. Si alza con HIIT 2-3×/settimana. È allenabile a ogni età.', tag: 'Longevità', fresh: false },
  { id: 'grip-strength', cat: 'longevita', emoji: '✊', punch: 'La forza di presa è un biomarcatore di invecchiamento', detail: 'Predice mortalità totale e cardiovascolare, indipendentemente dal resto. La alleni con deadlift, farmer\'s carry e prese isometriche. Target >40 kg (uomo), >25 kg (donna).', tag: 'Longevità', fresh: false },
  { id: 'decision-fatigue', cat: 'mente', emoji: '🧠', punch: '"Decision fatigue": regge molto meno di quanto si dica', detail: 'Su 200.000+ decisioni cliniche reali non emerge il calo di qualità previsto dalla teoria dell\'ego-depletion. Riorganizzare la giornata attorno a questo mito è tempo sprecato.', tag: 'Produttività', myth: true, fresh: false },
  { id: 'due-minuti', cat: 'mente', emoji: '✅', punch: 'La regola dei 2 minuti ha una base scientifica', detail: 'Masicampo & Baumeister (2011): chiudere subito i micro-task libera le risorse esecutive che altrimenti restano "occupate" dai compiti in sospeso (effetto Zeigarnik).', tag: 'Produttività', fresh: false },
  { id: 'alcol-sonno', cat: 'sonno', emoji: '🍷', punch: 'L\'alcol come sonnifero è un autogol', detail: 'Fa addormentare prima ma sopprime il sonno REM già da ~2 drink, e nella seconda metà della notte frammenta tutto. Stop almeno 3 ore prima di dormire.', tag: 'Sonno', myth: true, fresh: false },
  { id: 'alcol-jcurve', cat: 'cibo', emoji: '📉', punch: 'Il "bicchiere di vino fa bene" era un errore statistico', detail: 'La curva a J spariva correggendo il bias del "sick-quitter" (ex-bevitori malati contati come astemi). Chi non ha mai bevuto non ha rischio cardiovascolare maggiore.', tag: 'Alcol', myth: true, fresh: false },
  { id: 'plate-method', cat: 'cibo', emoji: '🍽️', punch: 'Il "metodo del piatto" ha dimezzato i farmaci in un trial', detail: 'Metà piatto verdure, un quarto proteine, un quarto carbo complessi: su 456 diabetici cinesi ha ridotto della metà il bisogno di farmaci. Semplice, niente conteggi.', tag: 'Glicemia', fresh: false },
  { id: 'leucina', cat: 'cibo', emoji: '🥩', punch: 'Dopo i 60 anni serve più leucina per lo stesso muscolo', detail: 'La risposta anabolica cala con l\'età: 25-30 g di proteine per pasto con ~2-3 g di leucina (whey su tutti) riaccendono la sintesi proteica. Timing post-allenamento ideale.', tag: 'Proteine', fresh: false },
  { id: 'nad-nmn', cat: 'integratori', emoji: '🔋', punch: 'NAD+ (NMN/NR): promettente ma non ancora "miracolo"', detail: 'NMN 250 mg/die per 12 settimane ha migliorato sonno e velocità di cammino in 65-75enni. I benefici umani restano modesti e sui biomarcatori: mancano studi lunghi.', tag: 'Longevità', myth: false, fresh: false },
  { id: 'vitd-respiratorie', cat: 'integratori', emoji: '🌞', punch: 'Vitamina D: scudo reale contro le infezioni respiratorie', detail: 'Meta-analisi di 43 RCT: effetto protettivo statisticamente significativo. Target 1000-2000 IU/die (di più se carente sotto 30 ng/mL). Verifica il basale prima.', tag: 'Immunità', fresh: false },
  { id: 'blue-light', cat: 'sonno', emoji: '🔵', punch: 'La luce blu serale schiaccia la melatonina', detail: 'A 446-477 nm la sopprime in modo dose-dipendente; la luce rossa quasi no. Spegni gli schermi 60-90 min prima, o usa night mode / filtri dopo il tramonto.', tag: 'Circadiano', fresh: false },
  { id: 'exercise-snacks', cat: 'allenamento', emoji: '🏃', punch: '"Exercise snacks": 2-3 min dopo i pasti tagliano la glicemia', detail: 'Brevi raffiche intense (squat, scale) subito dopo mangiato abbassano il picco glicemico del 20-30%. Non serve la palestra: bastano micro-sessioni sparse.', tag: 'Metabolismo', fresh: false },
  // ── Tornata 23 luglio 2026 — sonno, energia, cibi salutari, scoperte straordinarie ──
  { id: 'urolitina-a-immunita-2025', cat: 'integratori', emoji: '🛡️', punch: 'L\'urolitina A ricarica le cellule immunitarie stanche', detail: 'Nature Aging 2025: 1.000 mg/die per 4 settimane hanno aumentato del 14,7% la capacità dei linfociti CD8+ di bruciare grassi per energia, espandendo le cellule immunitarie meno esauste. Il beneficio principale non è muscolare, è immunitario.', tag: 'Mitofagia', fresh: false },
  { id: 'luce-ufficio-genere-2025', cat: 'sonno', emoji: '💡', punch: 'La luce d\'ufficio danneggia il sonno solo alle donne', detail: 'Chronobiology International 2025: ridurre intensità/spettro della luce diurna in ufficio ha peggiorato il sonno SOLO nelle donne; l\'effetto dipende dalla "storia di luce" dei giorni precedenti, non da una dose universale.', tag: 'Circadiano', myth: true, fresh: false },
  { id: 'colina-mitocondri-2026', cat: 'energia', emoji: '🧬', punch: 'Un solo lipide di membrana fa "invecchiare" i mitocondri', detail: 'Nature Communications 2026: il calo di fosfatidilcolina legato all\'età destabilizza la rete mitocondriale. Nei nematodi, integrare colina l\'ha ripristinata in 2 giorni — ancora solo su modello animale, non un consiglio per l\'uomo oggi.', tag: 'Mitocondri', fresh: false },
  { id: 'upf-vs-fresco-2025', cat: 'cibo', emoji: '🥗', punch: 'Stesse linee guida, dieta fresca dimagrisce il doppio', detail: 'Nature Medicine 2025: cibo ultra-processato e cibo fresco, ENTRAMBI conformi alle linee guida ufficiali — la dieta fresca ha prodotto 2,06% di calo peso contro l\'1,05% degli UPF in 8 settimane. Seguire le linee guida non basta, conta il grado di processazione.', tag: 'Ultra-processati', myth: true, fresh: false },
  { id: 'timing-pasti-genetica-2025', cat: 'cibo', emoji: '⏰', punch: 'Cenare tardi fa ingrassare, ma non tutti allo stesso modo', detail: 'Ogni ora di ritardo nei pasti aggiunge il 2,2% di peso in media — ma in chi ha alto rischio genetico di obesità l\'effetto sale a oltre 2 kg/m² di BMI per ora di ritardo. Per loro anticipare la cena è una leva potente, per altri è marginale.', tag: 'Timing pasti', fresh: false },
  { id: 'curcumina-butirrato-2025', cat: 'intestino', emoji: '🟡', punch: 'La curcuma nutre selettivamente i batteri "buoni" durante il dimagrimento', detail: 'RCT 2025: 500 mg/die di curcumina durante una dieta ipocalorica ha aumentato Faecalibacterium prausnitzii (produttore di butirrato) e impedito il crollo di diversità microbica tipico del dimagrimento — non solo "azione anti-infiammatoria" generica.', tag: 'Microbiota', fresh: false },
  { id: 'hsl-doppia-vita-2025', cat: 'longevita', emoji: '🔄', punch: 'Un enzima brucia-grassi ha una seconda vita nel nucleo della cellula', detail: 'Cell Metabolism 2025 risolve un paradosso di 60 anni: chi nasce senza HSL non ingrassa, anzi perde tessuto adiposo. La HSL ha un secondo ruolo nel nucleo degli adipociti, necessario per tenere in equilibrio il grasso corporeo stesso — scoperta solo su modelli animali.', tag: 'Scoperta', fresh: false },
  { id: 'senolitici-ossa-2024', cat: 'longevita', emoji: '🦴', punch: 'I senolitici rinforzano le ossa, ma solo a chi servono davvero', detail: 'Nature Medicine: in donne in post-menopausa, dasatinib+quercetina non ha aiutato il gruppo intero, ma chi aveva alto carico di cellule senescenti ha guadagnato +16% di formazione ossea — primo passo verso l\'anti-aging di precisione, non un integratore da provare da soli.', tag: 'Senescenza', fresh: false },
  // ── Tornata 23 luglio 2026 (bis) — solo scoperte CERTIFICATE pubblicate nel 2026, le più incredibili ──
  { id: 'staminali-fragilita-2026', cat: 'longevita', emoji: '💉', punch: 'Una singola infusione di cellule staminali fa camminare di più gli anziani fragili', detail: 'Cell Stem Cell, marzo 2026: 148 anziani fragili, un\'unica infusione di cellule mesenchimali da donatori giovani ha aumentato la distanza percorsa in 6 minuti di 63 metri (~20% in più) rispetto al placebo, a 9 mesi. Terapia ancora sperimentale (fase 2b).', tag: 'Rigenerazione', fresh: true },
  { id: 'superagers-neurogenesi-2026', cat: 'longevita', emoji: '🧠', punch: 'Chi invecchia con la memoria di un trentenne genera il doppio dei neuroni', detail: 'Nature, febbraio 2026: negli ippocampi post-mortem di "superagers" over-80 con memoria eccezionale c\'è il doppio di neuroni nuovi rispetto ai coetanei comuni, e 3 volte meno grovigli di tau. Prima prova diretta su tessuto umano che il cervello anziano continua a generare neuroni.', tag: 'Neurogenesi', fresh: true },
  { id: 'macrofagi-switch-2026', cat: 'longevita', emoji: '🔀', punch: 'Un singolo interruttore molecolare decide se una cellula immunitaria invecchia', detail: 'Nature Communications, febbraio 2026: bloccare una fosforilazione specifica su STAT6 fa invecchiare precocemente i macrofagi nei topi causando fibrosi; il mimetico opposto la riduce nettamente. Nei pazienti con BPCO lo stesso switch risulta già "spento".', tag: 'Senescenza cellulare', fresh: true },
  { id: 'neuroni-contenuto-contesto-2026', cat: 'mente', emoji: '🧩', punch: 'Il cervello non mescola "cosa" e "quando": usa due squadre di neuroni separate', detail: 'Nature, gennaio 2026: registrati 3.109 neuroni in pazienti con elettrodi impiantati — 597 neuroni codificano SOLO il contenuto (l\'oggetto), 200 SOLO il contesto (la regola). Si sincronizzano solo quando la risposta è corretta: ribalta 20 anni di teoria sulle "cellule concetto".', tag: 'Memoria', myth: true, fresh: true },
  { id: 'braingate-qwerty-2026', cat: 'mente', emoji: '⌨️', punch: 'Un impianto cerebrale fa scrivere quasi come su smartphone solo "pensandoci"', detail: 'Nature Neuroscience, marzo 2026: due pazienti con SLA/lesione al midollo hanno raggiunto 110 caratteri al minuto (22 parole/min, errore 1,6%) con un\'interfaccia cervello-computer, decodificando i movimenti delle dita — il doppio delle iBCI precedenti.', tag: 'Neurotecnologia', fresh: true },
  { id: 'c2orf74-obesita-2026', cat: 'longevita', emoji: '🧬', punch: 'Un gene "di fertilità" nei testicoli decide quanto grasso accumuli un uomo', detail: 'Nature Communications, maggio 2026: il gene C2orf74 (spermatogenesi) spegne la produzione di testosterone tramite un segnale dai testicoli, riducendo la trasformazione del grasso bianco in grasso che brucia calorie. Nei topi, disattivarlo protegge dall\'obesità da dieta — scoperta solo animale.', tag: 'Genetica metabolica', fresh: true },
  { id: 'fgf21-dimagrimento-2026', cat: 'energia', emoji: '🔥', punch: 'Scoperto l\'ormone che fa dimagrire bruciando calorie, non tagliando la fame', detail: 'Cell Reports, marzo 2026: FGF21 agisce su un circuito nel tronco encefalico (non l\'ipotalamo come si pensava) che aumenta la termogenesi. A differenza dei farmaci GLP-1 (riducono l\'appetito), questo meccanismo fa perdere peso senza mangiare meno — solo su topi finora.', tag: 'Metabolismo', myth: true, fresh: true },
  { id: 'microbiota-proteine-2026', cat: 'intestino', emoji: '🔬', punch: 'Non conta chi vive nell\'intestino, conta cosa sta facendo davvero', detail: 'Cell Metabolism, maggio 2026: mappate le PROTEINE (non solo i geni) di quasi 2.000 microbioti intestinali. Chi ha diabete/ipertensione ha un pattern specifico di proteine batteriche "spente" per l\'energia — spiega perché gli studi genetici sul microbiota davano risultati incoerenti.', tag: 'Microbiota', fresh: true },
];

// Categorie: chiave → etichetta, emoji, colore accento (per chip e bordi).
export const SCIENCE_CATEGORIES = [
  { key: 'sonno', label: 'Sonno', emoji: '🌙', color: '#818cf8' },
  { key: 'energia', label: 'Energia', emoji: '⚡', color: '#fbbf24' },
  { key: 'longevita', label: 'Longevità', emoji: '♾️', color: '#34d399' },
  { key: 'integratori', label: 'Integratori', emoji: '💊', color: '#f472b6' },
  { key: 'cibo', label: 'Cibo', emoji: '🍽️', color: '#fb923c' },
  { key: 'mente', label: 'Mente', emoji: '🧠', color: '#a78bfa' },
  { key: 'allenamento', label: 'Allenamento', emoji: '🔥', color: '#f87171' },
  { key: 'intestino', label: 'Intestino', emoji: '🦠', color: '#4ade80' },
];

export const scienceCategoryOf = (key) =>
  SCIENCE_CATEGORIES.find((c) => c.key === key) || { key, label: key, emoji: '🔬', color: '#94a3b8' };
