// ─────────────────────────────────────────────────────────────────────────────
//  NOVITÀ DAGLI STUDI — highlight curati a mano dai paper distillati.
//  A differenza di lib/knowledgeBase.js (auto-generato e sovrascritto dai tool),
//  questo file è editoriale: le "perle" più sorprendenti selezionate per la UI.
//  Ogni vota la ricerca notturna trova qualcosa di forte, si aggiunge qui una card.
// ─────────────────────────────────────────────────────────────────────────────

// cat: chiave categoria · icona/colore vivono in SCIENCE_CATEGORIES qui sotto.
// punch: il titolo-gancio (ciò che sorprende). detail: la sfumatura/come applicarlo.
// myth: true = sfata una credenza comune (badge speciale). fresh: false = ultima tornata.
export const SCIENCE_HIGHLIGHTS = [
  { id: 'caffeina-90min', cat: 'sonno', emoji: '☕', punch: 'Aspetta 90 minuti prima del primo caffè', detail: 'Il cortisolo naturale sale già del 50-75% nei primi 30-45 min dal risveglio. Ritardare la caffeina evita la sovrapposizione e riduce il crollo di metà mattina.', tag: 'Risveglio', fresh: false },
  { id: 'snooze-ok', cat: 'sonno', emoji: '⏰', punch: 'Lo snooze non è il nemico che credi', detail: 'Uno studio di Stoccolma (2023) mostra che 30 min di snooze non danneggiano il sonno e possono ridurre l\'inerzia del risveglio. Basta non abusarne: una volta sola.', tag: 'Risveglio', myth: true, fresh: false },
  { id: 'coffee-nap', cat: 'energia', emoji: '⚡', punch: 'Il "coffee nap" batte caffè e pisolino presi da soli', detail: 'Caffè + pisolino di 15-20 minuti insieme: la caffeina fa effetto proprio mentre ti svegli, sommando i due benefici. Vigilanza superiore a ciascuno separato.', tag: 'Energia', fresh: false },
  { id: 'adrenal-fatigue', cat: 'energia', emoji: '🚫', punch: '"Fatica surrenale": non esiste', detail: '58 studi la smontano: non c\'è evidenza che le surrenali si "esauriscano". La stanchezza cronica ha cause reali (sonno, ferro, tiroide, ME/CFS) da indagare, non un mito da integrare.', tag: 'Energia', myth: true, fresh: false },
  { id: 'butirrato', cat: 'intestino', emoji: '🦠', punch: 'Il butirrato spegne l\'infiammazione dall\'interno', detail: 'È il 20% degli acidi grassi a catena corta prodotti dai batteri: rinforza le tight junction intestinali e attiva i linfociti T regolatori. Lo nutri con fibre fermentabili (inulina, psillio, avena).', tag: 'Microbiota', fresh: false },
  { id: 'mediterranea-il6', cat: 'cibo', emoji: '🫒', punch: 'La dieta mediterranea abbassa IL-6 e CRP del 30%+', detail: 'Meta-analisi su 33 RCT (3.476 persone). E qui il dato forte: sul marcatore infiammatorio l\'intervento dietetico batte l\'esercizio da solo. Olio EVO come moltiplicatore.', tag: 'Anti-infiammazione', fresh: false },
  { id: 'mindfulness-cortisolo', cat: 'mente', emoji: '🧘', punch: '10-20 min di mindfulness abbassano il cortisolo misurato', detail: 'Meta-analisi su 35 trial: 25 mostrano cortisolo ridotto, 10 nessun effetto. Funziona, ma effetto piccolo-medio: rende di più abbinata a sonno ed esercizio.', tag: 'Stress', fresh: false },
  { id: 'cold-water', cat: 'allenamento', emoji: '🧊', punch: 'Acqua fredda: 10-15 min a 11-15°C è il punto ottimale', detail: 'Network meta-analisi 2025: quella finestra è la migliore per il dolore muscolare (DOMS), abbassa la creatina chinasi e migliora il salto. Più freddo di così = solo più scomodo.', tag: 'Recupero', fresh: false },
  { id: 'magnesio', cat: 'integratori', emoji: '💊', punch: 'Il magnesio lavora su sonno, muscoli e cuore insieme', detail: 'Blocca il calcio in eccesso nei neuroni: meno crampi, sonno più profondo. Carenza lieve legata a ipertensione e aritmie. Meglio glicinato/treonato, 300-400 mg la sera.', tag: 'Minerali', fresh: false },
  { id: 'creatina-anziani', cat: 'integratori', emoji: '🏋️', punch: 'La creatina fa guadagnare muscolo anche a 80 anni', detail: '3-5 g/die (niente fase di carico) + allenamento coi pesi: aumenta massa magra e forza pure in età avanzata. Uno dei 5-6 integratori con evidenza "alta" secondo l\'ISSN.', tag: 'Integratori', fresh: false },
  { id: 'vo2max', cat: 'longevita', emoji: '🫀', punch: 'Il VO2max predice la longevità meglio di quasi tutto', detail: 'Chi è nel gruppo "elite" di fitness ha ~5 volte meno mortalità del gruppo meno allenato. Si alza con HIIT 2-3×/settimana. È allenabile a ogni età.', tag: 'Longevità', fresh: false },
  { id: 'grip-strength', cat: 'longevita', emoji: '✊', punch: 'La forza di presa è un biomarcatore di invecchiamento', detail: 'Predice mortalità totale e cardiovascolare, indipendentemente dal resto. La alleni con deadlift, farmer\'s carry e prese isometriche. Target >40 kg (uomo), >25 kg (donna).', tag: 'Longevità', fresh: false },
  { id: 'decision-fatigue', cat: 'mente', emoji: '🧠', punch: '"Decision fatigue": regge molto meno di quanto si dica', detail: 'Su 200.000+ decisioni cliniche reali non emerge il calo di qualità previsto dalla teoria dell\'ego-depletion. Riorganizzare la giornata attorno a questo mito è tempo sprecato.', tag: 'Produttività', myth: true, fresh: false },
  { id: 'due-minuti', cat: 'mente', emoji: '✅', punch: 'La regola dei 2 minuti ha una base scientifica', detail: 'Masicampo & Baumeister (2011): chiudere subito i micro-task libera le risorse esecutive che altrimenti restano "occupate" dai compiti in sospeso (effetto Zeigarnik).', tag: 'Produttività', fresh: false },
  { id: 'alcol-sonno', cat: 'sonno', emoji: '🍷', punch: 'L\'alcol come sonnifero è un autogol', detail: 'Fa addormentare prima ma sopprime il sonno REM già da ~2 drink, e nella seconda metà della notte frammenta tutto. Stop almeno 3 ore prima di dormire.', tag: 'Sonno', myth: true, fresh: false },
  { id: 'alcol-jcurve', cat: 'cibo', emoji: '📉', punch: 'Il "bicchiere di vino fa bene" era un errore statistico', detail: 'La curva a J spariva correggendo il bias del "sick-quitter" (ex-bevitori malati contati come astemi). Chi non ha mai bevuto non ha rischio cardiovascolare maggiore.', tag: 'Alcol', myth: true, fresh: false },
  { id: 'plate-method', cat: 'cibo', emoji: '🍽️', punch: 'Il "metodo del piatto" ha dimezzato i farmaci in un trial', detail: 'Metà piatto verdure, un quarto proteine, un quarto carbo complessi: su 456 diabetici cinesi ha ridotto della metà il bisogno di farmaci. Semplice, niente conteggi.', tag: 'Glicemia', fresh: false },
  { id: 'leucina', cat: 'cibo', emoji: '🥩', punch: 'Dopo i 60 anni serve più leucina per lo stesso muscolo', detail: 'La risposta anabolica cala con l\'età: 25-30 g di proteine per pasto con ~2-3 g di leucina (whey su tutti) riaccendono la sintesi proteica. Timing post-allenamento ideale.', tag: 'Proteine', fresh: false },
  { id: 'nad-nmn', cat: 'integratori', emoji: '🔋', punch: 'NAD+ (NMN/NR): promettente ma non ancora "miracolo"', detail: 'NMN 250 mg/die per 12 settimane ha migliorato sonno e velocità di cammino in 65-75enni. I benefici umani restano modesti e sui biomarcatori: mancano studi lunghi.', tag: 'Longevità', myth: false, fresh: false },
  { id: 'vitd-respiratorie', cat: 'integratori', emoji: '🌞', punch: 'Vitamina D: scudo reale contro le infezioni respiratorie', detail: 'Meta-analisi di 43 RCT: effetto protettivo statisticamente significativo. Target 1000-2000 IU/die (di più se carente sotto 30 ng/mL). Verifica il basale prima.', tag: 'Immunità', fresh: false },
  { id: 'blue-light', cat: 'sonno', emoji: '🔵', punch: 'La luce blu serale schiaccia la melatonina', detail: 'A 446-477 nm la sopprime in modo dose-dipendente; la luce rossa quasi no. Spegni gli schermi 60-90 min prima, o usa night mode / filtri dopo il tramonto.', tag: 'Circadiano', fresh: false },
  { id: 'exercise-snacks', cat: 'allenamento', emoji: '🏃', punch: '"Exercise snacks": 2-3 min dopo i pasti tagliano la glicemia', detail: 'Brevi raffiche intense (squat, scale) subito dopo mangiato abbassano il picco glicemico del 20-30%. Non serve la palestra: bastano micro-sessioni sparse.', tag: 'Metabolismo', fresh: false },
  // ── Tornata 23 luglio 2026 — sonno, energia, cibi salutari, scoperte straordinarie ──
  { id: 'urolitina-a-immunita-2025', cat: 'integratori', emoji: '🛡️', punch: 'L\'urolitina A ricarica le cellule immunitarie stanche', detail: 'Nature Aging 2025: 1.000 mg/die per 4 settimane hanno aumentato del 14,7% la capacità dei linfociti CD8+ di bruciare grassi per energia, espandendo le cellule immunitarie meno esauste. Il beneficio principale non è muscolare, è immunitario.', tag: 'Mitofagia', fresh: false },
  { id: 'luce-ufficio-genere-2025', cat: 'sonno', emoji: '💡', punch: 'La luce d\'ufficio danneggia il sonno solo alle donne', detail: 'Chronobiology International 2025: ridurre intensità/spettro della luce diurna in ufficio ha peggiorato il sonno SOLO nelle donne; l\'effetto dipende dalla "storia di luce" dei giorni precedenti, non da una dose universale.', tag: 'Circadiano', myth: true, fresh: false },
  { id: 'colina-mitocondri-2026', cat: 'energia', emoji: '🧬', punch: 'Un solo lipide di membrana fa "invecchiare" i mitocondri', detail: 'Nature Communications 2026: il calo di fosfatidilcolina legato all\'età destabilizza la rete mitocondriale. Nei nematodi, integrare colina l\'ha ripristinata in 2 giorni — ancora solo su modello animale, non un consiglio per l\'uomo oggi.', tag: 'Mitocondri', fresh: false },
  { id: 'upf-vs-fresco-2025', cat: 'cibo', emoji: '🥗', punch: 'Stesse linee guida, dieta fresca dimagrisce il doppio', detail: 'Nature Medicine 2025: cibo ultra-processato e cibo fresco, ENTRAMBI conformi alle linee guida ufficiali — la dieta fresca ha prodotto 2,06% di calo peso contro l\'1,05% degli UPF in 8 settimane. Seguire le linee guida non basta, conta il grado di processazione.', tag: 'Ultra-processati', myth: true, fresh: false },
  { id: 'timing-pasti-genetica-2025', cat: 'cibo', emoji: '⏰', punch: 'Cenare tardi fa ingrassare, ma non tutti allo stesso modo', detail: 'Ogni ora di ritardo nei pasti aggiunge il 2,2% di peso in media — ma in chi ha alto rischio genetico di obesità l\'effetto sale a oltre 2 kg/m² di BMI per ora di ritardo. Per loro anticipare la cena è una leva potente, per altri è marginale.', tag: 'Timing pasti', fresh: false },
  { id: 'curcumina-butirrato-2025', cat: 'intestino', emoji: '🟡', punch: 'La curcuma nutre selettivamente i batteri "buoni" durante il dimagrimento', detail: 'RCT 2025: 500 mg/die di curcumina durante una dieta ipocalorica ha aumentato Faecalibacterium prausnitzii (produttore di butirrato) e impedito il crollo di diversità microbica tipico del dimagrimento — non solo "azione anti-infiammatoria" generica.', tag: 'Microbiota', fresh: false },
  { id: 'hsl-doppia-vita-2025', cat: 'longevita', emoji: '🔄', punch: 'Un enzima brucia-grassi ha una seconda vita nel nucleo della cellula', detail: 'Cell Metabolism 2025 risolve un paradosso di 60 anni: chi nasce senza HSL non ingrassa, anzi perde tessuto adiposo. La HSL ha un secondo ruolo nel nucleo degli adipociti, necessario per tenere in equilibrio il grasso corporeo stesso — scoperta solo su modelli animali.', tag: 'Scoperta', fresh: false },
  { id: 'senolitici-ossa-2024', cat: 'longevita', emoji: '🦴', punch: 'I senolitici rinforzano le ossa, ma solo a chi servono davvero', detail: 'Nature Medicine: in donne in post-menopausa, dasatinib+quercetina non ha aiutato il gruppo intero, ma chi aveva alto carico di cellule senescenti ha guadagnato +16% di formazione ossea — primo passo verso l\'anti-aging di precisione, non un integratore da provare da soli.', tag: 'Senescenza', fresh: false },
  // ── Tornata 23 luglio 2026 (bis) — solo scoperte CERTIFICATE pubblicate nel 2026, le più incredibili ──
  { id: 'staminali-fragilita-2026', cat: 'longevita', emoji: '💉', punch: 'Una singola infusione di cellule staminali fa camminare di più gli anziani fragili', detail: 'Cell Stem Cell, marzo 2026: 148 anziani fragili, un\'unica infusione di cellule mesenchimali da donatori giovani ha aumentato la distanza percorsa in 6 minuti di 63 metri (~20% in più) rispetto al placebo, a 9 mesi. Terapia ancora sperimentale (fase 2b).', tag: 'Rigenerazione', fresh: false },
  { id: 'superagers-neurogenesi-2026', cat: 'longevita', emoji: '🧠', punch: 'Chi invecchia con la memoria di un trentenne genera il doppio dei neuroni', detail: 'Nature, febbraio 2026: negli ippocampi post-mortem di "superagers" over-80 con memoria eccezionale c\'è il doppio di neuroni nuovi rispetto ai coetanei comuni, e 3 volte meno grovigli di tau. Prima prova diretta su tessuto umano che il cervello anziano continua a generare neuroni.', tag: 'Neurogenesi', fresh: false },
  { id: 'macrofagi-switch-2026', cat: 'longevita', emoji: '🔀', punch: 'Un singolo interruttore molecolare decide se una cellula immunitaria invecchia', detail: 'Nature Communications, febbraio 2026: bloccare una fosforilazione specifica su STAT6 fa invecchiare precocemente i macrofagi nei topi causando fibrosi; il mimetico opposto la riduce nettamente. Nei pazienti con BPCO lo stesso switch risulta già "spento".', tag: 'Senescenza cellulare', fresh: false },
  { id: 'neuroni-contenuto-contesto-2026', cat: 'mente', emoji: '🧩', punch: 'Il cervello non mescola "cosa" e "quando": usa due squadre di neuroni separate', detail: 'Nature, gennaio 2026: registrati 3.109 neuroni in pazienti con elettrodi impiantati — 597 neuroni codificano SOLO il contenuto (l\'oggetto), 200 SOLO il contesto (la regola). Si sincronizzano solo quando la risposta è corretta: ribalta 20 anni di teoria sulle "cellule concetto".', tag: 'Memoria', myth: true, fresh: false },
  { id: 'braingate-qwerty-2026', cat: 'mente', emoji: '⌨️', punch: 'Un impianto cerebrale fa scrivere quasi come su smartphone solo "pensandoci"', detail: 'Nature Neuroscience, marzo 2026: due pazienti con SLA/lesione al midollo hanno raggiunto 110 caratteri al minuto (22 parole/min, errore 1,6%) con un\'interfaccia cervello-computer, decodificando i movimenti delle dita — il doppio delle iBCI precedenti.', tag: 'Neurotecnologia', fresh: false },
  { id: 'c2orf74-obesita-2026', cat: 'longevita', emoji: '🧬', punch: 'Un gene "di fertilità" nei testicoli decide quanto grasso accumuli un uomo', detail: 'Nature Communications, maggio 2026: il gene C2orf74 (spermatogenesi) spegne la produzione di testosterone tramite un segnale dai testicoli, riducendo la trasformazione del grasso bianco in grasso che brucia calorie. Nei topi, disattivarlo protegge dall\'obesità da dieta — scoperta solo animale.', tag: 'Genetica metabolica', fresh: false },
  { id: 'fgf21-dimagrimento-2026', cat: 'energia', emoji: '🔥', punch: 'Scoperto l\'ormone che fa dimagrire bruciando calorie, non tagliando la fame', detail: 'Cell Reports, marzo 2026: FGF21 agisce su un circuito nel tronco encefalico (non l\'ipotalamo come si pensava) che aumenta la termogenesi. A differenza dei farmaci GLP-1 (riducono l\'appetito), questo meccanismo fa perdere peso senza mangiare meno — solo su topi finora.', tag: 'Metabolismo', myth: true, fresh: false },
  { id: 'microbiota-proteine-2026', cat: 'intestino', emoji: '🔬', punch: 'Non conta chi vive nell\'intestino, conta cosa sta facendo davvero', detail: 'Cell Metabolism, maggio 2026: mappate le PROTEINE (non solo i geni) di quasi 2.000 microbioti intestinali. Chi ha diabete/ipertensione ha un pattern specifico di proteine batteriche "spente" per l\'energia — spiega perché gli studi genetici sul microbiota davano risultati incoerenti.', tag: 'Microbiota', fresh: false },
  // ── Tornata 23 luglio 2026 (ter) — cose UTILI e attuabili per corporature alte, 20-25enni, Italia ──
  { id: 'creatina-dose-peso-2026', cat: 'integratori', emoji: '💊', punch: 'I 5g di creatina da etichetta sono tarati su un 70kg, non su di te', detail: 'Position stand ISSN: la dose standard assume ~70-75kg. Se pesi 85-90kg, la fase di carico corretta è 0,3 g/kg/die (25-27g, non 20g) per 5-7 giorni, mantenimento 0,075 g/kg di massa magra/die (6-7g, non 5g) — altrimenti non saturi davvero le riserve muscolari.', tag: 'Dose scalata', myth: true, fresh: false },
  { id: 'lombalgia-alti-2026', cat: 'allenamento', emoji: '📏', punch: 'Le persone alte non hanno solo più mal di schiena: rischiano il doppio la chirurgia', detail: 'Chi è nel quartile più alto di statura ha un rischio di CHIRURGIA lombare doppio (OR 2,01) contro un rischio di semplice lombalgia solo dell\'1,29 — le leve lunghe non danno solo fastidio, aumentano il rischio che degeneri. Mobilità dell\'anca e core anti-rotazione contano più della media.', tag: 'Leve lunghe', fresh: false },
  { id: 'tvp-altezza-2026', cat: 'longevita', emoji: '✈️', punch: 'Ogni 10cm di altezza in più, +27-45% di rischio di trombosi venosa', detail: 'Randomizzazione mendeliana (quindi causale): le gambe lunghe favoriscono la stasi venosa. Rilevante nei voli lunghi (alzati ogni 1-2h, calze a compressione) e dopo un infortunio sportivo con immobilizzazione prolungata — mobilizzazione precoce quando possibile.', tag: 'Rischio altezza', fresh: false },
  { id: 'sonno-testosterone-2026', cat: 'sonno', emoji: '😴', punch: 'Una settimana di sonno corto azzera parte del tuo picco ormonale a 20-25 anni', detail: '8 notti a 5h di sonno: testosterone giù del 10-15% in uomini giovani sani, in pochi GIORNI non mesi. A 20-25 anni il testosterone è al suo picco della vita — dormire meno di 7h lo sabota mentre lo stai ancora costruendo.', tag: 'Finestra giovane', fresh: false },
  { id: 'picco-osseo-2026', cat: 'longevita', emoji: '🦴', punch: 'A 23 anni la tua massa ossea si sta ancora costruendo, non solo mantenendo', detail: 'Coorte longitudinale: il picco di densità ossea aggiustata (BMAD) lombare arriva a 23,8 anni, quello femorale già a 21,2. Carico assiale (squat, stacco, salti) + calcio + vitamina D ORA costruiscono la base ossea che userai per i prossimi 40 anni — non si recupera dopo.', tag: 'Finestra giovane', fresh: false },
  { id: 'volume-natural-2026', cat: 'allenamento', emoji: '🏋️', punch: 'Oltre 20 serie a settimana per muscolo è solo fatica extra, non più massa', detail: 'Meta-regressione su 67 studi, 2.058 persone: l\'ipertrofia sale con il volume ma con rendimenti decrescenti oltre 12-20 serie/settimana per gruppo muscolare. Chi unisce palestra e arti marziali deve contare il volume TOTALE, non solo quello in sala pesi.', tag: 'Volume ottimale', myth: true, fresh: false },
  { id: 'vitd-italia-2026', cat: 'integratori', emoji: '🇮🇹', punch: 'In Italia da ottobre ad aprile il sole non ti dà vitamina D, punto', detail: 'Sopra il 34°-35° parallelo (tutta l\'Italia continentale, e quasi tutta la Sicilia d\'inverno) la sintesi cutanea di vitamina D è azzerata da novembre a febbraio, indipendentemente da quanto tempo stai al sole. Estate = carica le riserve (10-20 min, ore 11-15); inverno = serve integrazione, non più sole.', tag: 'Stagionalità IT', myth: true, fresh: false },
  { id: 'vitd-peso-2026', cat: 'integratori', emoji: '⚖️', punch: 'Se sei alto e muscoloso, la dose standard di vitamina D è troppo bassa', detail: 'RCT: 600 UI/die (dose standard) porta a soli 26 ng/mL di 25(OH)D dopo un anno, contro 36 ng/mL con 3.750 UI/die — la vitamina D si "diluisce" nella massa corporea totale. Per un fisico di 85-95kg, mantenimento invernale 2.000-4.000 UI/die, non 1.000-1.500.', tag: 'Dose scalata', fresh: false },
  { id: 'cena-italiana-2026', cat: 'sonno', emoji: '🍝', punch: 'La cena italiana delle 21:30 dopo l\'allenamento ti ruba sonno profondo', detail: 'Su 7.023 persone: orari dei pasti tardivi peggiorano la qualità soggettiva del sonno. Se ti alleni la sera e ceni tardi, hai meno di 3h prima di dormire. Anticipare la cena a fine allenamento (entro le 20:30) migliora sia il sonno profondo sia il recupero glicemico notturno.', tag: 'Timing IT', fresh: false },
  // ── Tornata 23 luglio 2026 (quater) — dosaggi scalati sul peso reale (85-90kg) + concurrent training + combat sport ──
  { id: 'proteine-plateau-2026', cat: 'cibo', emoji: '🥩', punch: 'Oltre 200g di proteine al giorno non ti fanno crescere di più', detail: 'Meta-analisi 49 RCT, 1.863 persone: il plateau per la massa magra è ~1,62 g/kg/die. Per 85-90kg: 138-198g/die è la fascia utile — sopra i 200g è spreco calorico, non un booster extra.', tag: 'Dose scalata', myth: true, fresh: true },
  { id: 'proteina-pasto-2026', cat: 'cibo', emoji: '🍗', punch: 'La regola dei "20-25g per pasto" è nata da uno studio sbagliato per te', detail: 'Quella regola veniva da esercizi isolati (solo gambe). Con allenamento whole-body (arti marziali + pesi), 40g di whey stimolano la sintesi proteica più di 20g. Punta a 35-40g per pasto dopo le sessioni whole-body.', tag: 'Dose scalata', myth: true, fresh: true },
  { id: 'caffeina-mgkg-2026', cat: 'allenamento', emoji: '☕', punch: 'La dose di caffeina che ti serve davvero si calcola sul tuo peso, non a occhio', detail: 'RCT su atleti di ju-jitsu: 3mg/kg aumenta salto ed esplosività misurabilmente. Per 85-90kg sono 255-270mg (3-3,5 espressi), 45-60 min prima dell\'allenamento — non "un caffè e via".', tag: 'Dose scalata', fresh: true },
  { id: 'sodio-sudore-2026', cat: 'allenamento', emoji: '🧂', punch: 'Una sessione intensa di arti marziali ti fa perdere fino a 2.500mg di sodio', detail: 'Dataset su 1.303 atleti: sport da combattimento sono tra i più sudati per intensità e gi. 1,5-2h di sessione intensa = 1,5-2L di sudore = 1000-2500mg di sodio da reintegrare con ~0,5-1g di sale extra nei pasti post-sessione.', tag: 'Elettroliti', fresh: true },
  { id: 'concurrent-6ore-2026', cat: 'allenamento', emoji: '⏱️', punch: 'Pesi e arti marziani lo stesso giorno? Servono almeno 6 ore di distanza', detail: 'RCT su 58 atleti: fare le due sessioni a 0 ore di distanza ha ridotto i guadagni di forza rispetto a farle con 6h o 24h di distanza (risultati sovrapponibili a chi faceva solo pesi). Sotto le 6 ore è la combinazione peggiore.', tag: 'Concurrent training', fresh: true },
  { id: 'concurrent-ordine-2026', cat: 'allenamento', emoji: '🔄', punch: 'Pesi prima o arti marziali prima? Con 3 ore di distanza non conta per forza e massa', detail: 'RCT 9 settimane: con 3h tra le sessioni l\'ordine non cambia forza/massa magra. Ma per la potenza esplosiva (utile per i colpi), fare prima i pesi e poi l\'attività di arti marziali dà un vantaggio leggero.', tag: 'Concurrent training', myth: true, fresh: true },
  { id: 'concurrent-interferenza-2026', cat: 'allenamento', emoji: '💪', punch: 'Le arti marziali non ti rubano forza o massa, solo un po\' di esplosività', detail: 'Meta-analisi 43 studi: l\'allenamento concorrente non riduce forza massimale né ipertrofia in modo significativo. L\'unico calo reale (-20/30%) è nella forza esplosiva se non gestisci bene volume e timing.', tag: 'Concurrent training', myth: true, fresh: true },
  { id: 'concurrent-glicogeno-2026', cat: 'allenamento', emoji: '🍚', punch: 'Poco glicogeno dopo le arti marziali blocca la crescita muscolare dai pesi', detail: 'A livello molecolare, l\'allenamento aerobico attiva AMPK che frena mTOR (la via della crescita muscolare) — ma solo se il glicogeno è basso. Rifornisciti di carboidrati + 20-40g proteine subito dopo ogni sessione per evitarlo.', tag: 'Concurrent training', fresh: true },
  { id: 'collagene-tendini-2026', cat: 'allenamento', emoji: '🦵', punch: 'Un cucchiaio di gelatina un\'ora prima protegge davvero i tendini', detail: 'Trial randomizzato: 15g di collagene + vitamina C, assunti 60 minuti PRIMA dell\'allenamento (non a caso), raddoppiano il marcatore di sintesi del collagene rispetto al placebo. Costo minimo, utile per chi fa striking/grappling regolare.', tag: 'Salute tendinea', fresh: true },
  { id: 'sparring-recupero-2026', cat: 'mente', emoji: '🥊', punch: 'Il cervello impiega 24 ore a riprendersi anche da uno sparring "leggero"', detail: 'In pugili amatoriali, 1 ora dopo lo sparring il controllo motorio e la memoria erano ancora alterati — tornati normali solo a 24 ore. Evita decisioni impegnative nelle 6h post-sparring e lascia almeno 24h prima del prossimo sparring alla testa.', tag: 'Recupero cerebrale', fresh: true },
  { id: 'infortuni-grappling-2026', cat: 'allenamento', emoji: '🤼', punch: 'Nel grappling le dita si infortunano più spesso, ma è il ginocchio quello serio', detail: 'Su 140 praticanti BJJ, l\'85,7% ha avuto almeno un infortunio: dita/mani le più colpite ma meno gravi, ginocchio più raro ma più serio. Per un fisico grande, investi su mobilità/stabilità del ginocchio e nastro preventivo sulle dita.', tag: 'Prevenzione infortuni', fresh: true },
];

// Categorie: chiave → etichetta, emoji, colore accento (per chip e bordi).
export const SCIENCE_CATEGORIES = [
  { key: 'sonno', label: 'Sonno', emoji: '🌙', color: '#818cf8' },
  { key: 'energia', label: 'Energia', emoji: '⚡', color: '#fbbf24' },
  { key: 'longevita', label: 'Longevità', emoji: '♾️', color: '#34d399' },
  { key: 'integratori', label: 'Integratori', emoji: '💊', color: '#f472b6' },
  { key: 'cibo', label: 'Cibo', emoji: '🍽️', color: '#fb923c' },
  { key: 'mente', label: 'Mente', emoji: '🧠', color: '#a78bfa' },
  { key: 'allenamento', label: 'Allenamento', emoji: '🔥', color: '#f87171' },
  { key: 'intestino', label: 'Intestino', emoji: '🦠', color: '#4ade80' },
];

export const scienceCategoryOf = (key) =>
  SCIENCE_CATEGORIES.find((c) => c.key === key) || { key, label: key, emoji: '🔬', color: '#94a3b8' };
